// End-to-end: parse the Kotelok fixture (5 files) with @alaq/graph, pipe the
// IR through @alaq/graph-zenoh, and assert on the generated Rust output.
//
// The snapshot test writes the file on first run and diffs against it on
// subsequent runs — identical to the link-state generator test harness.

import { beforeAll, describe, expect, test } from 'bun:test'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { compileSources } from '../../graph/src/index'
import { generate } from '../src/index'

const KOTELOK_DIR = join(import.meta.dir, '..', '..', 'graph', 'test', 'fixtures', 'kotelok')
const SNAPSHOT = join(import.meta.dir, 'snapshots', 'kotelok.rs.snap')

const FILES = ['identity.aql', 'players.aql', 'lobby.aql', 'round.aql', 'system.aql']

function loadFixture() {
  return FILES.map(n => ({
    path: join(KOTELOK_DIR, n),
    source: readFileSync(join(KOTELOK_DIR, n), 'utf8'),
  }))
}

let kotelokRust: string

beforeAll(() => {
  const res = compileSources(loadFixture())
  expect(res.ir).not.toBeNull()
  const errs = res.diagnostics.filter(d => d.severity === 'error')
  expect(errs).toEqual([])

  const gen = generate(res.ir!, { namespace: 'kotelok' })
  expect(gen.files.length).toBe(1)
  kotelokRust = gen.files[0].content
})

describe('Kotelok — end-to-end Rust generation', () => {
  test('output path is kotelok.rs', () => {
    const res = compileSources(loadFixture())
    const gen = generate(res.ir!, { namespace: 'kotelok' })
    expect(gen.files[0].path).toBe('kotelok.rs')
  })

  test('header + use imports present', () => {
    expect(kotelokRust).toContain('AUTOGENERATED by @alaq/graph-zenoh')
    expect(kotelokRust).toContain('use serde::{Serialize, Deserialize};')
    expect(kotelokRust).toContain('use zenoh::{Session, prelude::r#async::*};')
  })

  test('topics module with namespace constants', () => {
    expect(kotelokRust).toContain(`pub const NAMESPACE: &'static str = "kotelok";`)
    expect(kotelokRust).toContain(`pub const ACTION_PREFIX: &'static str = "kotelok/action";`)
  })

  test('all enums are emitted as Rust enums', () => {
    for (const name of ['RoomStatus', 'RoundPhase', 'WordOutcome']) {
      expect(kotelokRust).toContain(`pub enum ${name} {`)
    }
    // SCREAMING_SNAKE_CASE wire rename applied.
    expect(kotelokRust).toContain(`#[serde(rename_all = "SCREAMING_SNAKE_CASE")]`)
    // Variant names are PascalCase.
    expect(kotelokRust).toContain(`Lobby,`)
    expect(kotelokRust).toContain(`GameActive,`)
  })

  test('all records have pub struct <Name> declarations', () => {
    for (const name of [
      'Player', 'Team', 'GameRoom', 'GameSettings', 'WordSubmission',
      'RoundState', 'RoundStats', 'SystemInfo',
    ]) {
      expect(kotelokRust).toContain(`pub struct ${name} {`)
    }
  })

  test('camelCase SDL fields get #[serde(rename)] + snake_case on Rust side', () => {
    expect(kotelokRust).toContain(`#[serde(rename = "wordsPerPlayer")]`)
    expect(kotelokRust).toContain(`pub words_per_player: i64,`)
    expect(kotelokRust).toContain(`#[serde(rename = "myWords")]`)
    expect(kotelokRust).toContain(`pub my_words: Vec<String>,`)
    expect(kotelokRust).toContain(`#[serde(rename = "memberIds")]`)
    expect(kotelokRust).toContain(`pub member_ids: Vec<String>,`)
  })

  test('extend record fields are present on GameRoom (currentRound, currentTeamId)', () => {
    expect(kotelokRust).toMatch(/pub current_round: Option<RoundState>,/)
    expect(kotelokRust).toMatch(/pub current_team_id: Option<String>,/)
  })

  test('GameRoom gets SCOPE constant + scoped topic helper', () => {
    expect(kotelokRust).toContain(`pub const SCOPE: &'static str = "room";`)
    expect(kotelokRust).toContain(`pub fn topic(namespace: &str, id: &str) -> String {`)
    expect(kotelokRust).toContain(`format!("{}/room/{}/GameRoom", namespace, id)`)
  })

  test('unscoped SystemInfo gets topic(namespace) helper', () => {
    expect(kotelokRust).toMatch(/impl SystemInfo \{[\s\S]*?pub fn topic\(namespace: &str\) -> String/)
  })

  test('per-record publish + subscribe helpers emitted', () => {
    expect(kotelokRust).toContain(`pub async fn publish_game_room(`)
    expect(kotelokRust).toContain(`pub async fn subscribe_game_room<F>(`)
    expect(kotelokRust).toContain(`pub async fn publish_system_info(`)
  })

  test('scoped publisher signature takes id: &str', () => {
    expect(kotelokRust).toMatch(/publish_game_room\(\s*session: &Session,\s*namespace: &str,\s*id: &str,/)
  })

  test('unscoped publisher has no id arg', () => {
    const match = kotelokRust.match(/publish_system_info\([\s\S]*?\) -> zenoh::Result<\(\)>/)
    expect(match).not.toBeNull()
    expect(match![0]).not.toContain('id: &str')
  })

  test('action CreateRoom is unscoped with Input + Output', () => {
    expect(kotelokRust).toContain(`pub struct CreateRoomInput {`)
    expect(kotelokRust).toContain(`pub struct CreateRoomOutput(pub String);`)
    expect(kotelokRust).toContain(`pub async fn call_create_room(`)
    expect(kotelokRust).toContain(`format!("{}/action/CreateRoom", namespace)`)
  })

  test('action JoinRoom is scoped with room/id/action/JoinRoom topic', () => {
    expect(kotelokRust).toContain(`pub async fn call_join_room(`)
    expect(kotelokRust).toContain(`format!("{}/room/{}/action/JoinRoom", namespace, id)`)
    expect(kotelokRust).toContain(`pub struct JoinRoomOutput(pub Player);`)
  })

  test('action StartGame is fire-forget (no Output newtype, uses put)', () => {
    expect(kotelokRust).not.toContain(`StartGameOutput`)
    expect(kotelokRust).toContain(`pub fn start_game_topic(namespace: &str, id: &str)`)
    expect(kotelokRust).toContain(`pub async fn call_start_game(`)
  })

  test('field @auth(read: "owner") preserved as comment', () => {
    expect(kotelokRust).toContain(`// @auth(read: "owner")`)
  })

  test('realtime sub-field comment preserved', () => {
    expect(kotelokRust).toContain(`// @sync(qos: REALTIME)`)
  })

  test('cargo footer block included', () => {
    expect(kotelokRust).toContain(`Suggested Cargo.toml fragment:`)
    expect(kotelokRust).toContain(`zenoh = "0.11"`)
  })
})

describe('Kotelok snapshot', () => {
  test('matches stored snapshot byte-for-byte', () => {
    if (!existsSync(SNAPSHOT)) {
      writeFileSync(SNAPSHOT, kotelokRust)
      console.warn(`[snapshot] created ${SNAPSHOT}`)
      return
    }
    const stored = readFileSync(SNAPSHOT, 'utf8')
    if (stored !== kotelokRust) {
      const a = stored.split('\n')
      const b = kotelokRust.split('\n')
      const max = Math.max(a.length, b.length)
      for (let i = 0; i < max; i++) {
        if (a[i] !== b[i]) {
          console.error(`line ${i + 1}: expected ${JSON.stringify(a[i])}\n         got ${JSON.stringify(b[i])}`)
          break
        }
      }
    }
    expect(kotelokRust).toBe(stored)
  })
})

describe('core.identity namespace — scalars only', () => {
  test('emits pub type aliases for user scalars', () => {
    const res = compileSources(loadFixture())
    const gen = generate(res.ir!, { namespace: 'core.identity' })
    const src = gen.files[0].content
    expect(gen.files[0].path).toBe('core_identity.rs')
    expect(src).toContain('pub type UUID = String;')
    expect(src).toContain('pub type DeviceID = String;')
  })
})

describe('CRDT + atomic smoke test', () => {
  test('@crdt(LWW_MAP) emits merge/lww_key; @atomic emits encode_cbor/decode_cbor', () => {
    const src = `
      schema Test {
        version: 1
        namespace: "crdt_test"
      }
      record Message @crdt(type: LWW_MAP, key: "updated_at") {
        id: ID!
        text: String!
        updated_at: Timestamp!
      }
      record KalmanBlock @atomic {
        matrix: [Float!]!
        bias: [Float!]!
      }
    `
    const res = compileSources([{ path: 't.aql', source: src }])
    expect(res.diagnostics.filter(d => d.severity === 'error')).toEqual([])
    const gen = generate(res.ir!, { namespace: 'crdt_test' })
    const out = gen.files[0].content
    expect(out).toContain(`pub fn crdt_type() -> &'static str { "LWW_MAP" }`)
    expect(out).toContain(`pub fn lww_key(&self) -> i64 {`)
    expect(out).toContain(`self.updated_at`)
    expect(out).toContain(`pub fn merge(a: &Self, b: &Self) -> Self {`)
    expect(out).toContain(`pub fn encode_cbor(&self) -> Result<Vec<u8>, serde_cbor::Error> {`)
    expect(out).toContain(`pub fn decode_cbor(bytes: &[u8]) -> Result<Self, serde_cbor::Error> {`)
    // Cargo header advertises cbor + automerge deps because of the directives.
    expect(out).toContain(`serde_cbor = "0.11"`)
    expect(out).toContain(`automerge = "0.6"`)
  })

  test('unsupported CRDT type emits stub + warning', () => {
    const src = `
      schema Test {
        version: 1
        namespace: "or_set_test"
      }
      record Tags @crdt(type: OR_SET) {
        id: ID!
        values: [String!]!
      }
    `
    const res = compileSources([{ path: 't.aql', source: src }])
    const gen = generate(res.ir!, { namespace: 'or_set_test' })
    const out = gen.files[0].content
    expect(out).toContain(`// TODO: @crdt(type: OR_SET)`)
    const hasWarning = gen.diagnostics.some(d =>
      d.severity === 'warning' && d.message.includes('OR_SET'),
    )
    expect(hasWarning).toBe(true)
  })
})

describe('missing namespace', () => {
  test('emits an error diagnostic and zero files for unknown namespace', () => {
    const res = compileSources(loadFixture())
    const gen = generate(res.ir!, { namespace: 'does.not.exist' })
    expect(gen.files).toEqual([])
    expect(gen.diagnostics.some(d =>
      d.severity === 'error' && d.message.includes('does.not.exist'),
    )).toBe(true)
  })
})
