// End-to-end: parse the 5-file Kotelok fixture via @alaq/graph, pipe the
// IR through @alaq/graph-link-server, assert the output and compare
// against a stored snapshot. Mirrors the layout of the graph-link-state
// kotelok test so snapshot-maintenance workflows stay familiar.

import { test, expect, describe, beforeAll } from 'bun:test'
import { compileSources } from '../../graph/src/index'
import { generate } from '../src/index'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const KOTELOK_DIR = join(import.meta.dir, '..', '..', 'graph', 'test', 'fixtures', 'kotelok')
const SNAPSHOT = join(import.meta.dir, 'snapshots', 'kotelok.server.ts.snap')

// Same fixture as graph-link-state — multi-file, real-world shape.
const FILES = ['identity.aql', 'players.aql', 'lobby.aql', 'round.aql', 'system.aql']

function loadFixture() {
  return FILES.map(n => ({
    path: join(KOTELOK_DIR, n),
    source: readFileSync(join(KOTELOK_DIR, n), 'utf8'),
  }))
}

let kotelokSource: string

beforeAll(() => {
  const res = compileSources(loadFixture())
  expect(res.ir).not.toBeNull()
  const errs = res.diagnostics.filter(d => d.severity === 'error')
  expect(errs).toEqual([])

  const gen = generate(res.ir!, { namespace: 'kotelok' })
  expect(gen.files.length).toBe(1)
  kotelokSource = gen.files[0].content
})

describe('Kotelok — end-to-end generation (server)', () => {
  test('output includes header', () => {
    expect(kotelokSource).toContain('AUTOGENERATED by @alaq/graph-link-server')
    expect(kotelokSource).toContain('Schema: kotelok v1')
  })

  test('ActionContext is exported', () => {
    expect(kotelokSource).toContain('export interface ActionContext<')
    expect(kotelokSource).toContain('readonly peerId:')
    expect(kotelokSource).toContain('broadcastToRoom(')
    expect(kotelokSource).toContain('sendTo(')
  })

  test('ActionHandlers interface is exported', () => {
    expect(kotelokSource).toContain('export interface ActionHandlers {')
  })

  test('per-action signatures match SDL — scoped and unscoped', () => {
    // CreateRoom: unscoped, takes GameSettings input
    expect(kotelokSource).toMatch(
      /createRoom\(ctx: ActionContext(?:, input:[^)]+)?\):/,
    )
    // JoinRoom: scoped on room
    expect(kotelokSource).toContain(
      'joinRoom(ctx: ActionContext, roomId: string, input: { name: string }): IPlayer | Promise<IPlayer>',
    )
    // CreateTeam: scoped, returns Team
    expect(kotelokSource).toContain(
      'createTeam(ctx: ActionContext, roomId: string, input: { name: string }): ITeam | Promise<ITeam>',
    )
    // JoinTeam: scoped, boolean output
    expect(kotelokSource).toContain(
      'joinTeam(ctx: ActionContext, roomId: string, input: { teamId: string }): boolean | Promise<boolean>',
    )
    // SubmitWords: scoped, list input, boolean output
    expect(kotelokSource).toContain(
      'submitWords(ctx: ActionContext, roomId: string, input: { words: string[] }): boolean | Promise<boolean>',
    )
    // StartGame: scoped, no input, no output
    expect(kotelokSource).toContain(
      'startGame(ctx: ActionContext, roomId: string): void | Promise<void>',
    )
  })

  test('reachable records are embedded as I<Name>', () => {
    // Player is reachable via JoinRoom output → must be embedded.
    expect(kotelokSource).toContain('export interface IPlayer {')
    // Team is reachable via CreateTeam output.
    expect(kotelokSource).toContain('export interface ITeam {')
    // GameSettings is reachable via CreateRoom input.
    expect(kotelokSource).toContain('export interface IGameSettings {')
  })

  test('records NOT reachable from any action are omitted', () => {
    // GameRoom itself is scope-bound but never appears in action I/O.
    expect(kotelokSource).not.toContain('export interface IGameRoom {')
    // SystemInfo lives in a different namespace and must not appear.
    expect(kotelokSource).not.toContain('ISystemInfo')
  })

  test('dispatcher routes by action name with case arms', () => {
    expect(kotelokSource).toContain('export function createActionDispatcher(')
    expect(kotelokSource).toContain(`case 'CreateRoom':`)
    expect(kotelokSource).toContain(`case 'JoinRoom':`)
    expect(kotelokSource).toContain(`case 'CreateTeam':`)
    expect(kotelokSource).toContain(`case 'StartGame':`)
  })

  test('scope-bound case extracts room id from path', () => {
    expect(kotelokSource).toContain(`extractScopeId(path, 'room')`)
  })

  test('DispatcherOptions carries hooks for unknown action + error', () => {
    expect(kotelokSource).toContain('onUnknownAction?:')
    expect(kotelokSource).toContain('onError?:')
  })

  test('runtime import note surfaces the default (@alaq/link/server)', () => {
    expect(kotelokSource).toContain(`'@alaq/link/server'`)
  })
})

describe('Kotelok server snapshot', () => {
  test('matches stored snapshot byte-for-byte', () => {
    if (!existsSync(SNAPSHOT)) {
      writeFileSync(SNAPSHOT, kotelokSource)
      console.warn(`[snapshot] created ${SNAPSHOT}`)
      return
    }
    const stored = readFileSync(SNAPSHOT, 'utf8')
    if (stored !== kotelokSource) {
      const a = stored.split('\n')
      const b = kotelokSource.split('\n')
      const max = Math.max(a.length, b.length)
      for (let i = 0; i < max; i++) {
        if (a[i] !== b[i]) {
          console.error(`line ${i + 1}: expected ${JSON.stringify(a[i])}\n         got ${JSON.stringify(b[i])}`)
          break
        }
      }
    }
    expect(kotelokSource).toBe(stored)
  })
})

describe('empty / namespace handling', () => {
  test('ignores namespaces that have no actions (emits warning + empty stub)', () => {
    const res = compileSources(loadFixture())
    const gen = generate(res.ir!, { namespace: 'core.identity' })
    expect(gen.files.length).toBe(1)
    const warn = gen.diagnostics.find(d => d.severity === 'warning')
    expect(warn).toBeTruthy()
    expect(gen.files[0].content).toContain('export {}')
  })
})
