// @alaq/graph-link-server — file header + section helpers.

import { LineBuffer } from './utils'

export const GENERATOR_NAME = '@alaq/graph-link-server'
export const GENERATOR_VERSION = '0.1.0-draft'

export interface HeaderOptions {
  namespace: string
  schemaVersion: number
  runtimeImport: string
  header: boolean
}

/**
 * Emit the "AUTOGENERATED" banner. The server file is intentionally
 * self-contained — we do NOT import record interfaces from the client-side
 * `kotelok2.generated.ts`. Rationale: the server module often lives in a
 * separate tsconfig boundary and importing from the client bundle creates
 * an awkward build-order dependency. Instead, the record value shapes are
 * *embedded* (see types-gen.ts) — about 10 extra lines, one fewer cross-tree
 * import, and the server remains independent of Vue/client build choices.
 */
export function emitHeader(buf: LineBuffer, opts: HeaderOptions) {
  if (opts.header) {
    buf.line(`// AUTOGENERATED by ${GENERATOR_NAME} v${GENERATOR_VERSION}`)
    buf.line(`// Schema: ${opts.namespace} v${opts.schemaVersion}`)
    buf.line(`// DO NOT EDIT — regenerate from .aql sources`)
    buf.blank()
  }
  // No runtime imports needed: ActionContext, ActionHandlers and the
  // dispatcher are all type-only or free functions. The runtime import is
  // deferred to the `createActionDispatcher` signature — `@alaq/link`'s
  // `ServerMsg` / codec helpers are the caller's responsibility. This keeps
  // the generated file dependency-free in the TS module graph; the only
  // `import type` needed is for shared record interfaces, which we embed.
  buf.line(`// Runtime import: '${opts.runtimeImport}' (caller wires ServerMsg, codec).`)
  buf.blank()
}

export function emitSection(buf: LineBuffer, title: string) {
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.line(`// ${title}`)
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.blank()
}
