// @alaq/graph-link-server — public entry point.
//
// Reads an IR produced by `@alaq/graph` and emits TypeScript source with a
// typed `ActionHandlers` interface + `createActionDispatcher` function,
// ready to drop into `createLinkServer({ onAction })`.
//
// This package is the server-side sibling of `@alaq/graph-link-state`:
// same IR, different target. Output is self-contained — it does NOT import
// from the client-side generated module (see emit.ts for rationale).
//
// Pipeline:
//   compileSources(aql)        →   IR
//   generate(ir)               →   GenerateResult
//     · header
//     · embedded I<Record>     ← records reachable from action I/O
//     · ActionContext          ← broadcastToRoom / sendTo / peers
//     · ActionHandlers         ← one method per action
//     · createActionDispatcher ← routes by action name, extracts scope
//
// No runtime deps. Peer: `@alaq/graph`. Caller pairs the output with
// `@alaq/link/server` at consumer build-time.

import type {
  IR,
  IRAction,
  IRSchema,
} from '../../graph/src/types'
import {
  GENERATOR_NAME,
  GENERATOR_VERSION,
  emitHeader,
  emitSection,
} from './emit'
import { LineBuffer, buildTypeContext } from './utils'
import { emitActionContext } from './context-gen'
import { emitActionHandlers, emitEmbeddedRecords } from './handlers-gen'
import { emitDispatcher } from './dispatcher-gen'

// ────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────

export interface GenerateOptions {
  /** Target one namespace. When omitted, every namespace in the IR is emitted. */
  namespace?: string
  /** Runtime package the output will be paired with. Default: '@alaq/link/server'. */
  runtimeImport?: string
  /** Include the AUTOGENERATED banner at the top of each file. Default: true. */
  header?: boolean
  /**
   * Output file name (without directory). Defaults to `<namespace>.server.generated.ts`.
   * Handy when the caller emits the client and server files side-by-side and
   * wants a custom naming convention.
   */
  fileName?: string
  /**
   * Rename scope parameter per scope name. Called with the raw scope string
   * from SDL (`"room"`, `"team"`, ...). Default: `<scope>Id` (e.g. `roomId`).
   */
  scopeParamName?: (scope: string) => string
}

export interface GenerateDiagnostic {
  severity: 'error' | 'warning'
  message: string
}

export interface GenerateFile {
  path: string
  content: string
}

export interface GenerateResult {
  files: GenerateFile[]
  diagnostics: GenerateDiagnostic[]
}

const DEFAULT_SCOPE_PARAM = (scope: string) => `${scope}Id`

const DEFAULTS: Required<Omit<GenerateOptions, 'namespace' | 'fileName'>> = {
  runtimeImport: '@alaq/link/server',
  header: true,
  scopeParamName: DEFAULT_SCOPE_PARAM,
}

/**
 * Transform an IR into server-side TypeScript. Pure function — no FS, no
 * network, deterministic for a given IR + options.
 */
export function generate(ir: IR, options: GenerateOptions = {}): GenerateResult {
  const opts = { ...DEFAULTS, ...options }
  const files: GenerateFile[] = []
  const diagnostics: GenerateDiagnostic[] = []

  const namespaces = options.namespace
    ? [options.namespace]
    : Object.keys(ir.schemas).sort()

  for (const ns of namespaces) {
    const schema = ir.schemas[ns]
    if (!schema) {
      diagnostics.push({
        severity: 'error',
        message: `Namespace "${ns}" not found in IR.`,
      })
      continue
    }

    const content = generateNamespace(schema, opts, diagnostics)
    const path = options.fileName ?? `${ns}.server.generated.ts`
    files.push({ path, content })
  }

  return { files, diagnostics }
}

function generateNamespace(
  schema: IRSchema,
  opts: Required<Omit<GenerateOptions, 'namespace' | 'fileName'>>,
  diagnostics: GenerateDiagnostic[],
): string {
  const buf = new LineBuffer()
  emitHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    runtimeImport: opts.runtimeImport,
    header: opts.header,
  })

  const ctx = buildTypeContext(schema)
  const actions = schema.actions

  // When the schema has no actions, the server-side generator has nothing
  // useful to emit — surface a warning rather than an empty file so callers
  // that pipe `ir.json` through by mistake get a helpful signal.
  if (Object.keys(actions).length === 0) {
    diagnostics.push({
      severity: 'warning',
      message: `Namespace "${schema.namespace}" has no actions; server output will be empty.`,
    })
    buf.line(`// This schema declares no actions — no ActionHandlers to emit.`)
    buf.line(`export {}`)
    buf.blank()
    return buf.toString()
  }

  // ── Enums (embedded verbatim) ──
  // Server handlers may compare against enum members; emit a copy so the
  // generated file stays self-contained. Enum bodies are short and stable;
  // a duplicate on the server side beats an import from the client bundle.
  if (Object.keys(schema.enums).length > 0) {
    emitSection(buf, 'Enums (embedded from SDL)')
    const names = Object.keys(schema.enums).sort()
    for (const name of names) {
      const e = schema.enums[name]
      buf.line(`export enum ${e.name} {`)
      buf.indent()
      for (const member of e.values) {
        buf.line(`${member} = '${member}',`)
      }
      buf.dedent()
      buf.line(`}`)
      buf.blank()
    }
  }

  // ── User scalars (embedded as type aliases) ──
  if (Object.keys(schema.scalars).length > 0) {
    emitSection(buf, 'Scalars (user-defined, opaque strings)')
    const names = Object.keys(schema.scalars).sort()
    for (const name of names) {
      buf.line(`export type ${name} = string`)
    }
    buf.blank()
  }

  // ── Embedded record interfaces ──
  const reachable = countReachableRecords(actions, schema.records)
  if (reachable > 0) {
    emitSection(buf, 'Record value interfaces (embedded — no client import)')
    emitEmbeddedRecords(buf, actions, schema.records, ctx)
  }

  // ── ActionContext ──
  emitSection(buf, 'Action context (implemented by runtime adapter)')
  emitActionContext(buf)

  // ── ActionHandlers ──
  emitSection(buf, 'ActionHandlers — implement this to run the server')
  emitActionHandlers(buf, actions, ctx, opts.scopeParamName)

  // ── Dispatcher ──
  emitSection(buf, 'Dispatcher — plug into createLinkServer({ onAction })')
  emitDispatcher(buf, actions, ctx)

  return buf.toString()
}

function countReachableRecords(
  actions: Record<string, IRAction>,
  records: Record<string, unknown>,
): number {
  const set = new Set<string>()
  const walk = (typeName: string) => {
    if (records[typeName]) set.add(typeName)
  }
  for (const a of Object.values(actions)) {
    if (a.output) walk(a.output)
    for (const f of a.input ?? []) walk(f.type)
  }
  // Cheap count — the emitter re-computes the full reachability graph and
  // transitively expands. We just need "is there anything to emit at all".
  return set.size > 0 ? 1 : 0
}

// Re-export constants so tests / consumers can assert the version.
export { GENERATOR_NAME, GENERATOR_VERSION }

// Re-export IR types for downstream generator-of-generators ergonomics.
export type { IR, IRSchema, IRRecord, IRAction } from '../../graph/src/types'
