{
  "name": "@alaq/vue",
  "version": "6.0.0-alpha.4",
  "description": "Native Vue 3 reactivity bridge for Alaq Atoms and Nucleons",
  "type": "module",
  "keywords": [
    "vue",
    "reactive",
    "state",
    "atom",
    "nucl"
  ],
  "peerDependencies": {
    "vue": "^3.0.0"
  },
  "devDependencies": {
    "@alaq/nucl": "alpha",
    "@alaq/atom": "alpha",
    "vue": "^3.5.0"
  }
}
