// @alaq/graph-link-state — file header + assembly helpers.

import { LineBuffer } from './utils'

export const GENERATOR_NAME = '@alaq/graph-link-state'
export const GENERATOR_VERSION = '0.1.0-draft'

export interface HeaderOptions {
  namespace: string
  schemaVersion: number
  runtimeImport: string
  quarkImport: string
  header: boolean
}

/**
 * Emit the standard "AUTOGENERATED" banner + imports. Banner is suppressed
 * when `header: false` (useful for snapshot diffs or inlining).
 */
export function emitHeader(buf: LineBuffer, opts: HeaderOptions) {
  if (opts.header) {
    buf.line(`// AUTOGENERATED by ${GENERATOR_NAME} v${GENERATOR_VERSION}`)
    buf.line(`// Schema: ${opts.namespace} v${opts.schemaVersion}`)
    buf.line(`// DO NOT EDIT — regenerate from .aql sources`)
    buf.blank()
  }
  buf.line(`import type { ISyncNode, SyncStore, SyncListNode, SyncMapNode } from '${opts.runtimeImport}'`)
  buf.line(`import type { IQ } from '${opts.quarkImport}'`)
  buf.line(`import { createSyncNode, createListNode, createMapNode } from '${opts.runtimeImport}'`)
  buf.blank()
}

/**
 * Prepend a section divider comment. Purely cosmetic — makes the output
 * easier to skim.
 */
export function emitSection(buf: LineBuffer, title: string) {
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.line(`// ${title}`)
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.blank()
}
