// @alaq/graph-link-state — public entry point.
//
// Reads an IR produced by `@alaq/graph` and emits TypeScript code with
// typed wrappers around `@alaq/link-state`'s `SyncStore` / `SyncNode`.
//
// This package is transport-neutral: generated code talks only to the
// runtime it targets. Wire-specific behavior (Zenoh, Tauri, …) is in
// sibling generators.
//
// Output is a single `.ts` file per namespace. Each file is self-contained
// (header + imports + enums + interfaces + node facades + actions + api).

import type {
  IR,
  IRAction,
  IROpaque,
  IRRecord,
  IRSchema,
} from '@alaq/graph'
import { GENERATOR_NAME, GENERATOR_VERSION, emitHeader, emitSection } from './emit'
import { emitEnums } from './enums-gen'
import { emitInterfaces } from './types-gen'
import { emitNodes } from './nodes-gen'
import { emitActions } from './actions-gen'
import { emitApi } from './api-gen'
import { emitVueComposables, emitVueImports } from './vue-gen'
import { emitCrdtSchemaInto } from './crdt-schema-gen'
import { LineBuffer, buildTypeContext, hasDirective } from './utils'

// ────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────

export interface GenerateOptions {
  /** Target one namespace. When omitted, every namespace in the IR is emitted. */
  namespace?: string
  /** Import specifier for the runtime. Default: '@alaq/link-state'. */
  runtimeImport?: string
  /** Import specifier for the quark primitive (only `IQ` is used). */
  quarkImport?: string
  /** Include the AUTOGENERATED banner at the top of each file. Default: true. */
  header?: boolean
  /**
   * Split output into multiple files per namespace (types / nodes / actions).
   * v0.1 emits a single file regardless of this flag — the option is kept so
   * callers can opt in later without an API break.
   */
  splitFiles?: boolean
  /**
   * Emit Vue 3 composables for each record. Adds `use<Record>` /
   * `use<Record>InScope` helpers plus `Use<Record>Result` result types.
   * Requires `@alaq/link-state-vue` at consumer build time.
   * Default: false (generator stays Vue-free for non-Vue consumers).
   */
  vue?: boolean
  /** Import specifier for `@alaq/link-state-vue`. Only used when `vue: true`. */
  vueImport?: string
  /**
   * Emit a `<namespace>Schema: Record<string, FieldSchema>` const derived
   * from `@crdt` / `@sync` directives. Consumers pass it straight into
   * `new SyncBridge({ schema })`. Default: true (drift-free schema).
   * Set to false to keep the pre-v0.3 output shape for testability.
   */
  crdtSchema?: boolean
  /**
   * Import specifier for `FieldSchema`. Used only when `crdtSchema: true`.
   * Default: '@alaq/link' — once the root index re-exports the type
   * (FINDINGS §1.2), no consumer rewiring required. While that fix is in
   * flight, callers can point this at '@alaq/link/crdt' to bypass the
   * missing re-export.
   */
  fieldSchemaImport?: string
}

export interface GenerateDiagnostic {
  severity: 'error' | 'warning'
  message: string
}

export interface GenerateFile {
  path: string
  content: string
}

export interface GenerateResult {
  files: GenerateFile[]
  diagnostics: GenerateDiagnostic[]
}

const DEFAULTS: Required<Omit<GenerateOptions, 'namespace'>> = {
  runtimeImport: '@alaq/link-state',
  quarkImport: '@alaq/quark',
  header: true,
  splitFiles: false,
  vue: false,
  vueImport: '@alaq/link-state-vue',
  crdtSchema: true,
  // Point at the subpath by default until @alaq/link re-exports FieldSchema
  // from its root (tracked by Kotelok-2 FINDINGS §1.2). When that lands,
  // flip the default to '@alaq/link' in one commit.
  fieldSchemaImport: '@alaq/link/crdt',
}

/**
 * v0.3.4 (W8), tightened v0.3.5 (C7): transport kinds this generator emits
 * code for. `graph-link-state` sits on top of a WebSocket/HTTP-style
 * runtime; classified as `"http"` for the intent-check purposes of SPEC
 * §7.14. `"any"` is always compatible per R222. Schemas without `@transport`
 * are treated as `"any"` and suppress the check.
 */
const SUPPORTED_TRANSPORTS: ReadonlyArray<string> = ['http', 'any']

/**
 * Transform an IR into TypeScript source files. Pure function: no FS,
 * no network, deterministic for a given IR + options. The caller decides
 * where to write `files[*].path`.
 */
export function generate(ir: IR, options: GenerateOptions = {}): GenerateResult {
  const opts = { ...DEFAULTS, ...options }
  const files: GenerateFile[] = []
  const diagnostics: GenerateDiagnostic[] = []

  const namespaces = options.namespace
    ? [options.namespace]
    : Object.keys(ir.schemas).sort()

  for (const ns of namespaces) {
    const schema = ir.schemas[ns]
    if (!schema) {
      diagnostics.push({
        severity: 'error',
        message: `Namespace "${ns}" not found in IR.`,
      })
      continue
    }

    // v0.3.4 (W8), tightened v0.3.5 (C7): E025 on @transport mismatch —
    // generator refuses emission (SPEC §7.14 R221/R224). Unset / "any"
    // suppress per R222.
    if (schema.transport && !SUPPORTED_TRANSPORTS.includes(schema.transport)) {
      diagnostics.push({
        severity: 'error',
        message:
          `schema "${schema.namespace}" declares @transport(kind: "${schema.transport}") ` +
          `which is outside @alaq/graph-link-state supported transports [${SUPPORTED_TRANSPORTS.join(', ')}]; ` +
          `generation refused (E025). Set @transport(kind: "any") or omit the directive to opt out.`,
      })
      return { files: [], diagnostics }
    }

    const content = generateNamespace(schema, opts, diagnostics)
    // Namespaces like "core.identity" contain dots; Windows and bundlers
    // handle them fine, but keep one output file per namespace.
    files.push({ path: `${ns}.generated.ts`, content })
  }

  return { files, diagnostics }
}

/** v0.3.4 (W8): exported so tests/tooling can read the supported set. */
export { SUPPORTED_TRANSPORTS }

// ────────────────────────────────────────────────────────────────
// Namespace emitter
// ────────────────────────────────────────────────────────────────

function generateNamespace(
  schema: IRSchema,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
  diagnostics: GenerateDiagnostic[],
): string {
  const buf = new LineBuffer()
  emitHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    runtimeImport: opts.runtimeImport,
    quarkImport: opts.quarkImport,
    header: opts.header,
  })

  if (opts.vue) {
    emitVueImports(buf, {
      vueImport: opts.vueImport,
      runtimeImport: opts.runtimeImport,
    })
  }

  if (opts.crdtSchema) {
    // The `FieldSchema` import sits alongside the runtime/quark imports so
    // consumers using `noUnusedLocals` don't trip on it — the schema const
    // below references it directly.
    buf.line(`import type { FieldSchema } from '${opts.fieldSchemaImport}'`)
    buf.blank()
  }

  const ctx = buildTypeContext(schema)

  // ── Enums ──
  if (Object.keys(schema.enums).length > 0) {
    emitSection(buf, 'Enums')
    emitEnums(buf, schema.enums)
  }

  // ── User scalars (emitted as type aliases for clarity) ──
  if (Object.keys(schema.scalars).length > 0) {
    emitSection(buf, 'Scalars (user-defined, opaque strings)')
    const names = Object.keys(schema.scalars).sort()
    for (const name of names) {
      buf.line(`export type ${name} = string`)
    }
    buf.blank()
  }

  // ── Opaque streams (skeleton only, see TODO) ──
  const opaques = schema.opaques ?? {}
  if (Object.keys(opaques).length > 0) {
    emitSection(buf, 'Opaque streams (TODO: runtime support pending)')
    for (const name of Object.keys(opaques).sort()) {
      const o: IROpaque = opaques[name]
      buf.line(`// TODO: opaque stream ${o.name} (qos=${o.qos}${o.maxSize ? `, max_size=${o.maxSize}` : ''})`)
      diagnostics.push({
        severity: 'warning',
        message: `Opaque stream "${o.name}" is not yet supported by @alaq/graph-link-state (emitted as TODO comment).`,
      })
    }
    buf.blank()
  }

  // ── Interfaces ──
  if (Object.keys(schema.records).length > 0) {
    emitSection(buf, 'Record value interfaces')
    emitInterfaces(buf, schema.records, ctx)
  }

  // ── Node facades ──
  if (Object.keys(schema.records).length > 0) {
    emitSection(buf, 'SyncNode facades')
    emitNodes(buf, schema.records, schema.actions, ctx)
  }

  // ── Unscoped actions ──
  const hasUnscoped = Object.values(schema.actions).some(a => !a.scope)
  if (hasUnscoped) {
    emitSection(buf, 'Unscoped actions')
    emitActions(buf, schema.actions, ctx)
  }

  // ── Root API ──
  if (
    Object.keys(schema.records).length > 0 ||
    Object.keys(schema.actions).length > 0
  ) {
    emitSection(buf, 'Root API')
    emitApi(buf, schema.records, schema.actions)
  }

  // ── Vue composables (opt-in) ──
  if (opts.vue && Object.keys(schema.records).length > 0) {
    emitSection(buf, 'Vue composables')
    emitVueComposables(buf, schema.records)
  }

  // ── CRDT FieldSchema (opt-in, default on) ──
  // Goes last so consumers can skim the file top-to-bottom: types → nodes →
  // API → Vue → schema. The emitter no-ops the whole section when no
  // replicated records exist in the namespace; we probe a throwaway buffer
  // first to suppress an empty section divider in that case.
  if (opts.crdtSchema) {
    const probe = new LineBuffer()
    const willEmit = emitCrdtSchemaInto(probe, schema)
    if (willEmit) {
      emitSection(buf, 'CRDT schema (SyncBridge)')
      emitCrdtSchemaInto(buf, schema)
    }
  }

  // ── Warnings for directives we acknowledge but don't act on ──
  collectAdvisoryWarnings(schema, diagnostics)

  return buf.toString()
}

function collectAdvisoryWarnings(
  schema: IRSchema,
  diagnostics: GenerateDiagnostic[],
) {
  // These directives are intentionally "pass-through" in v0.1: the generator
  // preserves them as comments but does not alter types or runtime wiring.
  // Emitting a single warning per kind keeps output quiet while still signaling
  // "this is known, not forgotten".
  const passThroughSeen = new Set<string>()
  // v0.3: `@range` is now emitted as a JSDoc block (types-gen.ts), so it no
  // longer belongs in the "preserved as comment only" set. Same for
  // `@deprecated` — JSDoc's `@deprecated` is IDE-visible. `@auth` is also
  // JSDoc-emitted; runtime ACL wiring is still the runtime's job.
  const ignored = new Set(['store', 'liveness', 'added', 'topic'])

  const scan = (dirs: { name: string }[] | undefined) => {
    if (!dirs) return
    for (const d of dirs) {
      if (ignored.has(d.name) && !passThroughSeen.has(d.name)) {
        passThroughSeen.add(d.name)
        diagnostics.push({
          severity: 'warning',
          message: `Directive @${d.name} is preserved as a comment only in v0.1 of @alaq/graph-link-state.`,
        })
      }
    }
  }

  for (const rec of Object.values(schema.records)) {
    scan(rec.directives)
    for (const f of rec.fields) scan(f.directives)
  }
  for (const a of Object.values(schema.actions)) {
    scan(a.directives)
    for (const f of a.input ?? []) scan(f.directives)
  }
}

// Re-export the package constants so consumers/tests can assert version.
export { GENERATOR_NAME, GENERATOR_VERSION }

// ────────────────────────────────────────────────────────────────
// Deliberate non-export (used internally): keep graph types re-exported
// for ergonomic single-import from downstream generators-of-generators.
// ────────────────────────────────────────────────────────────────
export type { IR, IRSchema, IRRecord, IRAction } from '@alaq/graph'
