name: "@alaq/quark"
version: 6.0.0-alpha.0
description: High-performance proactive container with powerful plugin system
type: module
main: ./src/index.ts
types: ./dist/index.d.ts
scripts:
  build:types: tsc -p tsconfig.build.json
keywords:
  - state management
  - reactive
  - signals
  - store
  - atomic state
  - observable
  - quark
  - proactive
publishConfig:
  access: public
