// AUTOGENERATED by @alaq/graph-link-server v0.1.0-draft
// Schema: test v1
// DO NOT EDIT — regenerate from .aql sources

// Runtime import: '@alaq/link/server' (caller wires ServerMsg, codec).

// ────────────────────────────────────────────────────────────────
// Record value interfaces (embedded — no client import)
// ────────────────────────────────────────────────────────────────

export interface IPlayer {
  readonly id: string
  readonly name: string
}

// ────────────────────────────────────────────────────────────────
// Action context (implemented by runtime adapter)
// ────────────────────────────────────────────────────────────────

/**
 * Ambient context passed to every action handler. Implementations live
 * outside the generator — usually a thin adapter around
 * createLinkServer() that captures the peer map and codec.
 *
 * v0.1: no CRDT helpers, no request/reply timeout. See TODO.
 */
export interface ActionContext<TPeerId = string> {
  /** The peer who originated this action. Set by the dispatcher. */
  readonly peerId: TPeerId

  /**
   * Broadcast a raw (type, payload) message to every peer whose metadata
   * puts them in the given scope id. Pass excludeSelf=true to skip the
   * originator — useful for "notify others" style echoes.
   */
  broadcastToRoom(
    roomId: string,
    type: number,
    payload: unknown,
    excludeSelf?: boolean,
  ): void

  /** Send a direct message to one peer by id. No-op if the peer is gone. */
  sendTo(peerId: TPeerId, type: number, payload: unknown): void

  /** Iterate connected peer ids. Snapshot at call time — don't retain. */
  peers(): Iterable<TPeerId>
}

// ────────────────────────────────────────────────────────────────
// ActionHandlers — implement this to run the server
// ────────────────────────────────────────────────────────────────

/**
 * One method per action in the schema. Consumers 
 * implement this interface and pass it to createActionDispatcher().
 * Handlers may be sync or async; the dispatcher awaits either shape.
 */
export interface ActionHandlers {
  /**
   * action CreateRoom (unscoped)
   * input: { name: string }
   * output: string
   */
  createRoom(ctx: ActionContext, input: { name: string }): string | Promise<string>

  /**
   * action JoinRoom (scope "room")
   * input: { name: string }
   * output: IPlayer
   */
  joinRoom(ctx: ActionContext, roomId: string, input: { name: string }): IPlayer | Promise<IPlayer>

  /**
   * action LeaveRoom (scope "room")
   * output: void (fire-and-forget)
   */
  leaveRoom(ctx: ActionContext, roomId: string): void | Promise<void>

  /**
   * action Ping (unscoped)
   * output: void (fire-and-forget)
   */
  ping(ctx: ActionContext): void | Promise<void>
}

// ────────────────────────────────────────────────────────────────
// Dispatcher — plug into createLinkServer({ onAction })
// ────────────────────────────────────────────────────────────────

export interface DispatcherOptions {
  /** Handler table. One method per action in the SDL. */
  handlers: ActionHandlers
  /** Base context. The dispatcher shallow-overrides `peerId` per call. */
  ctx: Omit<ActionContext, 'peerId'> & { peerId?: string }
  /** Called when no handler matches. Default: throw. */
  onUnknownAction?: (action: string, path: string) => unknown
  /** Called when a handler throws. Default: rethrow. */
  onError?: (action: string, error: unknown) => unknown
}

/**
 * Strip the "${scope}." prefix from a wire path. Returns the raw
 * path when the prefix does not match — the handler will likely
 * treat that as invalid and throw, but we stay permissive so a
 * misrouted message can't crash the server.
 */
function extractScopeId(path: string, scope: string): string {
  const prefix = scope + '.'
  return path.startsWith(prefix) ? path.slice(prefix.length) : path
}

/**
 * Wire generated handlers to createLinkServer()'s onAction callback.
 *
 * Usage:
 *   const server = createLinkServer({
 *     port: 3456,
 *     onAction: createActionDispatcher({ handlers, ctx }),
 *   })
 */
export function createActionDispatcher(options: DispatcherOptions) {
  return async (
    action: string,
    path: string,
    args: unknown,
    peerId: string,
  ): Promise<unknown> => {
    const peerCtx: ActionContext = { ...options.ctx, peerId }
    try {
      switch (action) {
        case 'CreateRoom': {
          const input = args as { name: string }
          return await options.handlers.createRoom(peerCtx, input)
        }
        case 'JoinRoom': {
          const scopeId = extractScopeId(path, 'room')
          const input = args as { name: string }
          return await options.handlers.joinRoom(peerCtx, scopeId, input)
        }
        case 'LeaveRoom': {
          const scopeId = extractScopeId(path, 'room')
          return await options.handlers.leaveRoom(peerCtx, scopeId)
        }
        case 'Ping': {
          return await options.handlers.ping(peerCtx)
        }
        default: {
          if (options.onUnknownAction) return options.onUnknownAction(action, path)
          throw new Error(`[dispatcher] unknown action: ${action}`)
        }
      }
    } catch (err) {
      if (options.onError) return options.onError(action, err)
      throw err
    }
  }
}

