import { IR, Namespace } from '@alaq/graph';

export interface GenerateOptions {
  header?: boolean;
  clientImport?: string;
}

export function generate(ir: IR, options: GenerateOptions = {}) {
  const files: { path: string; content: string }[] = [];
  const header = options.header !== false;
  const clientImport = options.clientImport || '@alaq/link-http-client';

  for (const ns of ir.namespaces) {
    files.push({
      path: `${ns.name}.http.generated.ts`,
      content: generateNamespace(ns, { header, clientImport }),
    });
  }

  return { files };
}

function generateNamespace(ns: Namespace, opts: { header: boolean; clientImport: string }) {
  const lines: string[] = [];

  if (opts.header) {
    lines.push(`/**`);
    lines.push(` * @generated by @alaq/graph-link-http`);
    lines.push(` * Namespace: ${ns.name}`);
    lines.push(` */`);
  }

  lines.push(`import { callAction, type HttpClientOptions } from '${opts.clientImport}';`);
  lines.push(``);

  // Enums
  for (const e of ns.enums) {
    lines.push(`export enum ${e.name} {`);
    for (const v of e.variants) {
      lines.push(`  ${v} = '${v}',`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  // Records
  for (const r of ns.records) {
    lines.push(`export interface I${r.name} {`);
    for (const f of r.fields) {
      const type = mapType(f.type);
      lines.push(`  readonly ${f.name}${f.required ? '' : '?'}: ${type};`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  // Action Inputs
  for (const a of ns.actions) {
    lines.push(`export interface I${a.name}Input {`);
    for (const f of a.input) {
      const type = mapType(f.type);
      lines.push(`  readonly ${f.name}${f.required ? '' : '?'}: ${type};`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  // Action Wrappers
  for (const a of ns.actions) {
    const outputType = a.output ? mapType(a.output) : 'void';
    lines.push(`export async function ${camelCase(a.name)}(`);
    lines.push(`  options: HttpClientOptions,`);
    lines.push(`  input: I${a.name}Input,`);
    lines.push(`): Promise<${outputType}> {`);
    lines.push(`  return callAction<I${a.name}Input, ${outputType}>(options, '${snakeCase(a.name)}', input);`);
    lines.push(`}`);
    lines.push(``);
  }

  // Factory
  lines.push(`export function createHttpApi(options: HttpClientOptions) {`);
  lines.push(`  return {`);
  for (const a of ns.actions) {
    lines.push(`    ${camelCase(a.name)}: (input: I${a.name}Input) => ${camelCase(a.name)}(options, input),`);
  }
  lines.push(`  };`);
  lines.push(`}`);

  return lines.join('\n');
}

function mapType(type: any): string {
  // Simplified type mapping for brevity
  switch (type.kind) {
    case 'Scalar':
      switch (type.name) {
        case 'String': return 'string';
        case 'Int':
        case 'Float': return 'number';
        case 'Boolean': return 'boolean';
        default: return 'any';
      }
    case 'Record':
    case 'Enum':
      return type.name.startsWith('I') ? type.name : (type.kind === 'Record' ? 'I' + type.name : type.name);
    case 'List':
      return `${mapType(type.item)}[]`;
    default:
      return 'any';
  }
}

function camelCase(s: string) {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function snakeCase(s: string) {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}
