import { IR, IRSchema } from '@alaq/graph';

export interface GenerateOptions {
  header?: boolean;
  rtCrate?: string;
  namespace?: string;
}

export function generate(ir: IR, options: GenerateOptions = {}) {
  const files: { path: string; content: string }[] = [];
  const header = options.header !== false;
  const rtCrate = options.rtCrate || 'alaq_link_http_client';

  const namespaces = options.namespace 
    ? [options.namespace] 
    : Object.keys(ir.schemas).sort();

  for (const nsName of namespaces) {
    const schema = ir.schemas[nsName];
    if (!schema) continue;

    const dirName = schema.namespace.replace(/\./g, '_');
    files.push({
      path: `${dirName}/mod.rs`,
      content: generateMod(schema, { header, rtCrate }),
    });
  }

  return { files };
}

function generateMod(ns: IRSchema, opts: { header: boolean; rtCrate: string }) {
  const lines: string[] = [];

  if (opts.header) {
    lines.push(`/*`);
    lines.push(` * @generated by @alaq/graph-link-http-rs`);
    lines.push(` * Namespace: ${ns.namespace}`);
    lines.push(` */`);
  }

  lines.push(`use serde::{Deserialize, Serialize};`);
  lines.push(`use ${opts.rtCrate}::{HttpClient, AlaqHttpError};`);
  lines.push(``);

  // Enums
  for (const e of Object.values(ns.enums)) {
    lines.push(`#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]`);
    lines.push(`pub enum ${e.name} {`);
    for (const v of e.values) {
      lines.push(`    ${v},`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  // Records
  for (const r of Object.values(ns.records)) {
    lines.push(`#[derive(Debug, Clone, Serialize, Deserialize)]`);
    lines.push(`pub struct ${r.name} {`);
    for (const f of r.fields) {
      const type = mapRustType(f.type, f.required);
      lines.push(`    pub ${f.name}: ${type},`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  // Action Inputs
  for (const a of Object.values(ns.actions)) {
    lines.push(`#[derive(Debug, Clone, Serialize, Deserialize, Default)]`);
    lines.push(`pub struct ${a.name}Input {`);
    if (a.input) {
      for (const f of a.input) {
        const type = mapRustType(f.type, f.required);
        lines.push(`    pub ${f.name}: ${type},`);
      }
    }
    lines.push(`}`);
    lines.push(``);
  }

  // Client Struct
  const rawName = ns.namespace.split('.').pop() || 'Client';
  const clientName = `${pascalCase(rawName)}Client`;
  lines.push(`pub struct ${clientName} {`);
  lines.push(`    inner: HttpClient,`);
  lines.push(`}`);
  lines.push(``);

  lines.push(`impl ${clientName} {`);
  lines.push(`    pub fn new(base_url: String) -> Self {`);
  lines.push(`        Self { inner: HttpClient::new(base_url) }`);
  lines.push(`    }`);
  lines.push(``);
  lines.push(`    pub fn with_token(mut self, token: String) -> Self {`);
  lines.push(`        self.inner = self.inner.with_token(token);`);
  lines.push(`        self`);
  lines.push(`    }`);
  lines.push(``);

  for (const a of Object.values(ns.actions)) {
    const outputType = a.output ? mapRustType(a.output as any, true) : '()';
    lines.push(`    pub async fn ${snakeCase(a.name)}(&self, input: ${a.name}Input) -> Result<${outputType}, AlaqHttpError> {`);
    lines.push(`        self.inner.call_action("${snakeCase(a.name)}", input).await`);
    lines.push(`    }`);
    lines.push(``);
  }
  lines.push(`}`);

  return lines.join('\n');
}

function pascalCase(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function mapRustType(type: any, required: boolean): string {
  let base: string;
  if (typeof type === 'string') {
    base = type;
  } else {
    switch (type.kind) {
      case 'Scalar':
        switch (type.name) {
          case 'String': base = 'String'; break;
          case 'Int': base = 'i32'; break;
          case 'Float': base = 'f64'; break;
          case 'Boolean': base = 'bool'; break;
          default: base = 'serde_json::Value'; break;
        }
        break;
      case 'Record':
      case 'Enum':
        base = type.name;
        break;
      case 'List':
        base = `Vec<${mapRustType(type.item, true)}>`;
        break;
      case 'TypeRef':
        base = type.name;
        break;
      default:
        base = 'serde_json::Value';
    }
  }

  return required ? base : `Option<${base}>`;
}

function snakeCase(s: string) {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}
