// @alaq/graph-tauri-rs — per-file headers / footers.
//
// Every generated `.rs` file gets an AUTOGENERATED banner plus an `allow`
// attribute list so pre-run lint noise doesn't blow up `cargo build`. Actual
// `use` imports live in the module-specific emitters (types/handlers/commands/
// register/events) to keep each file self-contained — Tauri code traditionally
// `use`-s at the top of the file.

import { LineBuffer } from './utils'
// `_version.ts` is a build artifact synced from `package.yaml` by
// `alak/scripts/sync-generator-versions.ts`. Regenerated on every
// `bun run build:types` via the `prebuild:types` hook.
export { GENERATOR_NAME, GENERATOR_VERSION } from './_version'
import { GENERATOR_NAME, GENERATOR_VERSION } from './_version'

export interface HeaderOptions {
  namespace: string
  schemaVersion: number
  fileRole: string
  header: boolean
}

export function emitFileHeader(buf: LineBuffer, opts: HeaderOptions) {
  if (opts.header) {
    buf.line(`// AUTOGENERATED by ${GENERATOR_NAME} v${GENERATOR_VERSION}`)
    buf.line(`// Schema: ${opts.namespace} v${opts.schemaVersion}`)
    buf.line(`// File:   ${opts.fileRole}`)
    buf.line(`// DO NOT EDIT — regenerate from .aql sources`)
    buf.blank()
  }
  buf.line(`#![allow(dead_code, unused_imports, unused_variables, clippy::all)]`)
  buf.blank()
}

export function emitSection(buf: LineBuffer, title: string) {
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.line(`// ${title}`)
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.blank()
}
