// @alaq/graph-tauri-rs — public entry point.
//
// Consumes an IR from `@alaq/graph` and emits one Rust module per namespace,
// laid out as five files under `generated/<ns_flat>/`:
//
//   mod.rs       — re-exports + `use` glue
//   types.rs     — records + enums + user scalars + Input structs; `AppError`
//                  is `pub use`-d from the runtime crate (one canonical copy).
//   handlers.rs  — `<Ns>Handlers` async trait
//   commands.rs  — `#[tauri::command]` delegators
//   register.rs  — `register_<ns>_commands!()` macro wrapping tauri::generate_handler!
//   events.rs    — STUB (see events-gen.ts — waits on P.1 / IR leadingComments)
//
// Paths in `GenerateResult.files` are repo-root-relative (e.g.
// `generated/belladonna_reader/types.rs`); the caller writes them under its
// `src-tauri/src/` folder.
//
// Pure function: deterministic for (IR, options). No I/O, no network.

import type {
  IR,
  IRAction,
  IRRecord,
  IRSchema,
} from '@alaq/graph'
import { GENERATOR_NAME, GENERATOR_VERSION, emitFileHeader, emitSection } from './emit'
import {
  emitActionInputs,
  emitAppError,
  emitEnums,
  emitEventPayloads,
  emitRecords,
  emitUserScalars,
} from './types-gen'
import { emitHandlers, handlersTraitName } from './handlers-gen'
import { emitCommands } from './commands-gen'
import { emitRegister, registerMacroName } from './register-gen'
import { emitEvents } from './events-gen'
import { LineBuffer, buildTypeContext, nsFlat } from './utils'

// ────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────

export interface GenerateOptions {
  /** Target one namespace. When omitted, every namespace in the IR is emitted. */
  namespace?: string
  /** Emit the AUTOGENERATED banner on each file. Default true. */
  header?: boolean
  /** Name of the runtime crate (for future `use rtCrate::…` imports). */
  rtCrate?: string
  /** Handlers DI mode. `trait` (default) or `functions` (unimplemented). */
  handlersMode?: 'trait' | 'functions'
}

export interface GenerateDiagnostic {
  severity: 'error' | 'warning'
  message: string
}

export interface GenerateFile {
  path: string
  content: string
}

export interface GenerateResult {
  files: GenerateFile[]
  diagnostics: GenerateDiagnostic[]
}

const DEFAULTS: Required<Omit<GenerateOptions, 'namespace'>> = {
  header: true,
  rtCrate: 'alaq_graph_tauri_rt',
  handlersMode: 'trait',
}

/**
 * v0.3.4 (W8), tightened v0.3.5 (C7): transport kinds this generator emits
 * code for. Compared against `IRSchema.transport` (projected from
 * `@transport(kind: "...")`, SPEC §7.14). Mismatch → E025 error, generator
 * returns `files: []`. `"any"` is always compatible — schemas without
 * `@transport` are treated as `"any"` per R222.
 */
const SUPPORTED_TRANSPORTS: ReadonlyArray<string> = ['tauri', 'any']

export function generate(ir: IR, options: GenerateOptions = {}): GenerateResult {
  const opts = { ...DEFAULTS, ...options }
  const files: GenerateFile[] = []
  const diagnostics: GenerateDiagnostic[] = []

  if (opts.handlersMode === 'functions') {
    diagnostics.push({
      severity: 'error',
      message:
        `handlersMode: 'functions' is not implemented in @alaq/graph-tauri-rs v0.1. ` +
        `Only 'trait' mode is supported. See packages/graph-tauri-rs/README.md.`,
    })
    return { files, diagnostics }
  }

  const namespaces = options.namespace
    ? [options.namespace]
    : Object.keys(ir.schemas).sort()

  for (const ns of namespaces) {
    const schema = ir.schemas[ns]
    if (!schema) {
      diagnostics.push({
        severity: 'error',
        message: `Namespace "${ns}" not found in IR.`,
      })
      continue
    }
    // v0.3.4 (W8), tightened v0.3.5 (C7): E025 on @transport mismatch —
    // generator refuses emission (SPEC §7.14 R221/R224). Unset / "any"
    // suppress per R222.
    if (schema.transport && !SUPPORTED_TRANSPORTS.includes(schema.transport)) {
      diagnostics.push({
        severity: 'error',
        message:
          `schema "${schema.namespace}" declares @transport(kind: "${schema.transport}") ` +
          `which is outside @alaq/graph-tauri-rs supported transports [${SUPPORTED_TRANSPORTS.join(', ')}]; ` +
          `generation refused (E025). Set @transport(kind: "any") or omit the directive to opt out.`,
      })
      return { files: [], diagnostics }
    }
    emitNamespace(schema, opts, files, diagnostics)
  }

  return { files, diagnostics }
}

/** v0.3.4 (W8): exported so tests/tooling can read the supported set. */
export { SUPPORTED_TRANSPORTS }

// ────────────────────────────────────────────────────────────────
// Per-namespace emission
// ────────────────────────────────────────────────────────────────

function emitNamespace(
  schema: IRSchema,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
  files: GenerateFile[],
  diagnostics: GenerateDiagnostic[],
) {
  const base = `generated/${nsFlat(schema.namespace)}`
  const ctx = buildTypeContext(schema)

  files.push({
    path: `${base}/types.rs`,
    content: emitTypesFile(schema, ctx, opts),
  })
  files.push({
    path: `${base}/handlers.rs`,
    content: emitHandlersFile(schema, ctx, opts),
  })
  files.push({
    path: `${base}/commands.rs`,
    content: emitCommandsFile(schema, ctx, opts),
  })
  files.push({
    path: `${base}/register.rs`,
    content: emitRegisterFile(schema, opts),
  })
  files.push({
    path: `${base}/events.rs`,
    content: emitEventsFile(schema, ctx, opts),
  })
  files.push({
    path: `${base}/mod.rs`,
    content: emitModFile(schema, opts),
  })

  // Advisory: if any action carries an unknown/non-implemented directive,
  // surface it so user knows the generator ignored it. Mirrors graph-zenoh.
  collectAdvisoryWarnings(schema, diagnostics)
}

// ────────────────────────────────────────────────────────────────
// File emitters (per role)
// ────────────────────────────────────────────────────────────────

function emitTypesFile(
  schema: IRSchema,
  ctx: ReturnType<typeof buildTypeContext>,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    fileRole: 'types.rs (records, enums, scalars, Input structs, AppError re-export)',
    header: opts.header,
  })
  buf.line(`use serde::{Serialize, Deserialize};`)
  buf.blank()

  if (Object.keys(schema.scalars).length > 0) {
    emitSection(buf, 'Scalars (user-defined, opaque strings)')
    emitUserScalars(buf, schema.scalars)
  }

  if (Object.keys(schema.enums).length > 0) {
    emitSection(buf, 'Enums')
    emitEnums(buf, schema.enums)
  }

  if (Object.keys(schema.records).length > 0) {
    emitSection(buf, 'Records')
    emitRecords(buf, schema.records, ctx)
  }

  // v0.3.4 / W9 — event payload structs live in `types.rs` next to records
  // so they can be `use`-d uniformly from handlers / events.rs / user code.
  if (Object.keys(schema.events).length > 0) {
    emitSection(buf, 'Event payloads')
    emitEventPayloads(buf, schema.events, ctx)
  }

  if (Object.keys(schema.actions).length > 0) {
    emitSection(buf, 'Action Input structs')
    emitActionInputs(buf, schema.actions, ctx)
  }

  emitAppError(buf, opts.rtCrate)

  return buf.toString()
}

function emitHandlersFile(
  schema: IRSchema,
  ctx: ReturnType<typeof buildTypeContext>,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    fileRole: 'handlers.rs (user-implemented async trait)',
    header: opts.header,
  })
  // Every action Input comes from the sibling types module; AppError too.
  buf.line(`use super::types::*;`)
  buf.blank()
  if (Object.keys(schema.actions).length === 0) {
    buf.line(`// No actions in this namespace → no Handlers trait to emit.`)
    return buf.toString()
  }
  emitSection(buf, 'Handlers trait')
  emitHandlers(buf, schema.name, schema.namespace, schema.actions, ctx)
  return buf.toString()
}

function emitCommandsFile(
  schema: IRSchema,
  ctx: ReturnType<typeof buildTypeContext>,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    fileRole: 'commands.rs (Tauri command delegators)',
    header: opts.header,
  })
  buf.line(`use super::types::*;`)
  buf.line(`use super::handlers::*;`)
  buf.blank()
  if (Object.keys(schema.actions).length === 0) {
    buf.line(`// No actions in this namespace → no commands to emit.`)
    return buf.toString()
  }
  emitSection(buf, 'Tauri command delegators')
  emitCommands(buf, schema.name, schema.actions, ctx)
  return buf.toString()
}

function emitRegisterFile(
  schema: IRSchema,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    fileRole: 'register.rs (register_<ns>_commands! macro)',
    header: opts.header,
  })
  emitSection(buf, 'Register macro')
  emitRegister(buf, schema.namespace, schema.actions)
  return buf.toString()
}

function emitEventsFile(
  schema: IRSchema,
  ctx: ReturnType<typeof buildTypeContext>,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    fileRole: 'events.rs (broadcast emit_<event> helpers)',
    header: opts.header,
  })
  emitEvents(buf, schema.namespace, schema.events, ctx)
  return buf.toString()
}

function emitModFile(
  schema: IRSchema,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    fileRole: 'mod.rs (re-exports)',
    header: opts.header,
  })
  buf.line(`pub mod types;`)
  buf.line(`pub mod handlers;`)
  buf.line(`pub mod commands;`)
  buf.line(`pub mod register;`)
  buf.line(`pub mod events;`)
  buf.blank()
  buf.line(`pub use types::*;`)
  if (Object.keys(schema.actions).length > 0) {
    buf.line(`pub use handlers::*;`)
    buf.line(`pub use commands::*;`)
  }
  buf.blank()
  buf.line(`// Register macro is exported at crate root via \`#[macro_export]\`:`)
  buf.line(`//   ${registerMacroName(schema.namespace)}!()`)
  buf.line(`// Pair with .manage::<Arc<dyn ${handlersTraitName(schema.namespace)}>>(…).`)
  buf.blank()
  return buf.toString()
}

// ────────────────────────────────────────────────────────────────
// Advisory warnings for preserved-but-unused directives
// ────────────────────────────────────────────────────────────────

function collectAdvisoryWarnings(
  schema: IRSchema,
  diagnostics: GenerateDiagnostic[],
) {
  const seen = new Set<string>()
  // v0.1 preserves these as documentation comments only.
  const ignored = new Set(['auth', 'store', 'liveness', 'range', 'deprecated', 'added', 'sync', 'crdt', 'atomic', 'topic', 'scope'])

  const scan = (dirs: { name: string }[] | undefined) => {
    if (!dirs) return
    for (const d of dirs) {
      if (ignored.has(d.name) && !seen.has(d.name)) {
        seen.add(d.name)
        diagnostics.push({
          severity: 'warning',
          message: `Directive @${d.name} is preserved as a comment only in v0.1 of @alaq/graph-tauri-rs.`,
        })
      }
    }
  }

  for (const rec of Object.values(schema.records)) {
    scan(rec.directives)
    for (const f of rec.fields) scan(f.directives)
  }
  for (const a of Object.values(schema.actions)) {
    scan(a.directives)
    for (const f of a.input ?? []) scan(f.directives)
  }
}

// ────────────────────────────────────────────────────────────────
// Re-exports
// ────────────────────────────────────────────────────────────────

export { GENERATOR_NAME, GENERATOR_VERSION }
export type { IR, IRSchema, IRRecord, IRAction } from '@alaq/graph'
