// End-to-end: parse Belladonna's reader.aql via @alaq/graph, feed the IR
// into @alaq/graph-tauri, assert the expected TS wrappers are emitted.
//
// C5 (2026-04-21): the byte-for-byte snapshot compare was dropped — it
// flapped on every unrelated version bump / keyword-table edit. The
// structural regex/contains checks below still pin down every interesting
// fact about the emitted module, and an opt-in `tsc --noEmit` integration
// test (ALAK_INT_TESTS=1) guards the compiles-at-all invariant.

import { test, expect, describe, beforeAll } from 'bun:test'
import { parseSource } from '../../graph/src/index'
import { generate } from '../src/index'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'

const READER_AQL = join(
  import.meta.dir,
  '..', '..', '..', '..',
  'pharos', 'Belladonna', 'schema', 'reader.aql',
)

let generated: string

beforeAll(() => {
  const src = readFileSync(READER_AQL, 'utf8')
  const res = parseSource(src, 'reader.aql')
  expect(res.ir).not.toBeNull()
  const errs = res.diagnostics.filter(d => d.severity === 'error')
  expect(errs).toEqual([])

  const gen = generate(res.ir!, { namespace: 'belladonna.reader' })
  expect(gen.files.length).toBe(1)
  generated = gen.files[0].content
})

describe('reader.aql → @alaq/graph-tauri', () => {
  test('emits header + tauri invoke import', () => {
    expect(generated).toContain('AUTOGENERATED by @alaq/graph-tauri')
    expect(generated).toContain(`import { invoke } from '@tauri-apps/api/core'`)
  })

  test('record interfaces with readonly fields', () => {
    for (const name of ['ITocEntry', 'IRenderedDoc', 'IViewHistoryEntry', 'IBundleManifest']) {
      expect(generated).toContain(`export interface ${name} {`)
    }
    expect(generated).toContain(`readonly html: string`)
    expect(generated).toContain(`readonly last_opened: number`)
    // Map<String, String> → Record<string, string>
    expect(generated).toContain(`readonly contexts: Record<string, string>`)
    // Nested list of records stays as `ITocEntry[]`
    expect(generated).toContain(`readonly toc: ITocEntry[]`)
  })

  test('action input interfaces are emitted (including empty ones)', () => {
    for (const name of [
      'IRenderMarkdownInput',
      'IRecordViewInput',
      'IGetViewHistoryInput',
      'IOpenInExplorerInput',
      'IOpenBundleInput',
    ]) {
      expect(generated).toContain(`export interface ${name} {`)
    }
    // OpenBundle has optional context
    expect(generated).toContain(`readonly context?: string`)
  })

  test('action wrapper: name camelCased, invoke command snake_cased', () => {
    expect(generated).toMatch(
      /export async function renderMarkdown\(input: IRenderMarkdownInput\): Promise<IRenderedDoc>/,
    )
    expect(generated).toContain(`invoke<IRenderedDoc>('render_markdown', { input })`)
  })

  test('list output → T[] Promise', () => {
    expect(generated).toMatch(
      /export async function getViewHistory\(input: IGetViewHistoryInput\): Promise<IViewHistoryEntry\[\]>/,
    )
    expect(generated).toContain(`invoke<IViewHistoryEntry[]>('get_view_history', { input })`)
  })

  test('fire-and-forget action (no output) resolves to void', () => {
    expect(generated).toMatch(
      /export async function recordView\(input: IRecordViewInput\): Promise<void>/,
    )
    expect(generated).toContain(`await invoke('record_view', { input })`)
  })

  test('boolean output', () => {
    expect(generated).toMatch(
      /export async function openBundle\(input: IOpenBundleInput\): Promise<boolean>/,
    )
    expect(generated).toContain(`invoke<boolean>('open_bundle', { input })`)
  })

  test('createTauriApi bundles every action', () => {
    expect(generated).toContain(`export function createTauriApi()`)
    expect(generated).toContain(`renderMarkdown: (input: IRenderMarkdownInput) => renderMarkdown(input)`)
    expect(generated).toContain(`recordView: (input: IRecordViewInput) => recordView(input)`)
    expect(generated).toContain(`openBundle: (input: IOpenBundleInput) => openBundle(input)`)
  })

  test('events placeholder present when schema declares none, state stub still present', () => {
    // reader.aql declares no `event` blocks. W9 onward: events generator
    // leaves a tiny placeholder rather than an `__eventsNotSupported`
    // export — adding the first event grows the section into real typed
    // `on<EventName>` listeners.
    expect(generated).toContain(`No \`event\` declarations in this namespace`)
    expect(generated).toContain(`__stateNotSupported`)
  })
})

// ────────────────────────────────────────────────────────────────
// Opt-in: compile-check the emitted file via `tsc --noEmit`.
// Enable with ALAK_INT_TESTS=1. Skipped by default — running tsc on
// every bun-test invocation is too slow for the tight loop.
// ────────────────────────────────────────────────────────────────

const INT_TESTS = process.env.ALAK_INT_TESTS === '1'

describe.if(INT_TESTS)('reader.aql → tsc --noEmit', () => {
  test('emitted TypeScript type-checks', () => {
    const tmp = mkdtempSync(join(tmpdir(), 'alak-tauri-int-'))
    try {
      // Stub the only external import: @tauri-apps/api/core.
      const stubDir = join(tmp, 'node_modules', '@tauri-apps', 'api')
      // prettier-ignore
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      require('node:fs').mkdirSync(stubDir, { recursive: true })
      writeFileSync(
        join(stubDir, 'core.ts'),
        'export function invoke<T>(_cmd: string, _args?: unknown): Promise<T> { return Promise.reject(); }',
      )
      writeFileSync(
        join(stubDir, 'event.ts'),
        [
          'export type UnlistenFn = () => void',
          'export function listen<T>(_name: string, _cb: (ev: { payload: T }) => void): Promise<UnlistenFn> {',
          '  return Promise.resolve(() => {})',
          '}',
        ].join('\n'),
      )

      // Write the generated file + a minimal tsconfig.
      writeFileSync(join(tmp, 'generated.ts'), generated)
      writeFileSync(
        join(tmp, 'tsconfig.json'),
        JSON.stringify(
          {
            compilerOptions: {
              target: 'ES2022',
              module: 'ESNext',
              moduleResolution: 'Bundler',
              strict: true,
              noEmit: true,
              skipLibCheck: true,
              paths: {
                '@tauri-apps/api/core': ['./node_modules/@tauri-apps/api/core.ts'],
                '@tauri-apps/api/event': ['./node_modules/@tauri-apps/api/event.ts'],
              },
            },
            include: ['generated.ts'],
          },
          null,
          2,
        ),
      )

      const r = spawnSync(process.platform === 'win32' ? 'bunx.cmd' : 'bunx', ['tsc', '--noEmit', '-p', tmp], {
        encoding: 'utf8',
        stdio: 'pipe',
        shell: false,
      })
      if (r.status !== 0) {
        console.error('tsc stdout:\n' + r.stdout)
        console.error('tsc stderr:\n' + r.stderr)
      }
      expect(r.status).toBe(0)
    } finally {
      rmSync(tmp, { recursive: true, force: true })
    }
  }, 180_000)
})
