#!/usr/bin/env bun
// sync-generator-versions.ts — eliminates version drift between the
// `GENERATOR_VERSION` constant embedded in emitted files' headers and the
// package's actual `package.yaml` version.
//
// For each generator package listed below:
//   1. Read `<pkg>/package.yaml` → `{name, version}`.
//   2. Write `<pkg>/src/_version.ts` with:
//        export const GENERATOR_NAME = '<name>'
//        export const GENERATOR_VERSION = '<version>'
//   3. `src/emit.ts` imports both from `./_version`.
//
// `_version.ts` is a build artifact — it's listed in each package's
// `.gitignore` and regenerated on every `bun run build:types` via the
// `prebuild:types` hook wired through bun's `pre<script>` convention.
//
// Run: `bun scripts/sync-generator-versions.ts`

import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import * as YAML from 'yaml'

const PACKAGES_ROOT = resolve(import.meta.dir, '..', 'packages')

/**
 * Packages whose generators embed `GENERATOR_NAME` / `GENERATOR_VERSION`
 * constants in the header of every emitted file. Keep the list tight:
 * adding a package here means committing to the `src/_version.ts` +
 * `.gitignore` contract.
 */
const GENERATOR_PACKAGES = [
  'graph-axum',
  'graph-tauri-rs',
  'graph-tauri',
]

interface PackageYaml {
  name: string
  version: string
}

function readPackageYaml(pkgDir: string): PackageYaml {
  const pkgPath = join(pkgDir, 'package.yaml')
  const parsed = YAML.parse(readFileSync(pkgPath, 'utf8')) as PackageYaml
  if (!parsed.name || !parsed.version) {
    throw new Error(`[sync-generator-versions] ${pkgPath} is missing name/version`)
  }
  return { name: parsed.name, version: parsed.version }
}

function writeVersionFile(pkgDir: string, info: PackageYaml): string {
  const outPath = join(pkgDir, 'src', '_version.ts')
  const content =
    `// AUTOGENERATED by alak/scripts/sync-generator-versions.ts — DO NOT EDIT.\n` +
    `// Re-run \`bun scripts/sync-generator-versions.ts\` (or \`bun run build:types\`\n` +
    `// in this package) to refresh.\n` +
    `//\n` +
    `// Source of truth: ./package.yaml { name, version }\n` +
    `\n` +
    `export const GENERATOR_NAME = ${JSON.stringify(info.name)}\n` +
    `export const GENERATOR_VERSION = ${JSON.stringify(info.version)}\n`
  writeFileSync(outPath, content)
  return outPath
}

function main() {
  let updated = 0
  for (const pkg of GENERATOR_PACKAGES) {
    const pkgDir = join(PACKAGES_ROOT, pkg)
    const info = readPackageYaml(pkgDir)
    const outPath = writeVersionFile(pkgDir, info)
    console.log(`[sync-generator-versions] ${pkg}: ${info.name}@${info.version} → ${outPath}`)
    updated += 1
  }
  console.log(`[sync-generator-versions] OK — ${updated} package(s) in sync.`)
}

main()
