// End-to-end: parse the 5-file Kotelok fixture via @alaq/graph, pipe the IR
// through @alaq/graph-link-state, assert the output and compare against a
// stored snapshot.

import { test, expect, describe, beforeAll } from 'bun:test'
import { compileSources } from '../../graph/src/index'
import { generate } from '../src/index'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const KOTELOK_DIR = join(import.meta.dir, '..', '..', 'graph', 'test', 'fixtures', 'kotelok')
const SNAPSHOT = join(import.meta.dir, 'snapshots', 'kotelok.ts.snap')

const FILES = ['identity.aql', 'players.aql', 'lobby.aql', 'round.aql', 'system.aql']

function loadFixture() {
  return FILES.map(n => ({
    path: join(KOTELOK_DIR, n),
    source: readFileSync(join(KOTELOK_DIR, n), 'utf8'),
  }))
}

let kotelokSource: string

beforeAll(() => {
  const res = compileSources(loadFixture())
  expect(res.ir).not.toBeNull()
  const errs = res.diagnostics.filter(d => d.severity === 'error')
  expect(errs).toEqual([])

  const gen = generate(res.ir!, { namespace: 'kotelok' })
  expect(gen.files.length).toBe(1)
  kotelokSource = gen.files[0].content
})

describe('Kotelok — end-to-end generation', () => {
  test('output includes header + imports', () => {
    expect(kotelokSource).toContain('AUTOGENERATED by @alaq/graph-link-state')
    expect(kotelokSource).toContain(`from '@alaq/link-state'`)
    expect(kotelokSource).toContain(`from '@alaq/quark'`)
  })

  test('all enums are emitted', () => {
    for (const name of ['RoomStatus', 'RoundPhase', 'WordOutcome']) {
      expect(kotelokSource).toContain(`export enum ${name} {`)
    }
    expect(kotelokSource).toContain(`LOBBY = 'LOBBY'`)
  })

  test('all records have I<Name> interfaces', () => {
    for (const name of [
      'IPlayer', 'ITeam', 'IGameRoom', 'IGameSettings', 'IWordSubmission',
      'IRoundState', 'IRoundStats', 'ISystemInfo',
    ]) {
      expect(kotelokSource).toContain(`export interface ${name} {`)
    }
  })

  test('all records have <Name>Node facades + factories', () => {
    for (const name of [
      'Player', 'Team', 'GameRoom', 'GameSettings', 'WordSubmission',
      'RoundState', 'RoundStats', 'SystemInfo',
    ]) {
      expect(kotelokSource).toContain(`export interface ${name}Node {`)
      expect(kotelokSource).toContain(`export function create${name}Node(`)
    }
  })

  test('extend record fields are present (currentRound, currentTeamId)', () => {
    expect(kotelokSource).toMatch(/readonly currentRound\?: IRoundState/)
    expect(kotelokSource).toMatch(/readonly currentTeamId\?: string/)
  })

  test('GameRoom is scoped — factory takes id', () => {
    expect(kotelokSource).toContain(
      'export function createGameRoomNode(store: SyncStore, id: string): GameRoomNode',
    )
    expect(kotelokSource).toContain('const path = `room.${id}`')
  })

  test('scoped actions become methods on GameRoomNode', () => {
    for (const sig of [
      'joinRoom(input: { name: string }): Promise<IPlayer>',
      'createTeam(input: { name: string }): Promise<ITeam>',
      'joinTeam(input: { teamId: string }): Promise<boolean>',
      'submitWords(input: { words: string[] }): Promise<boolean>',
      'startGame(): Promise<void>',
      'playerReady(): Promise<boolean>',
      'guessWord(): Promise<boolean>',
      'skipWord(): Promise<boolean>',
      'confirmRound(): Promise<boolean>',
      'fixScore(input: { word: string, outcome: WordOutcome }): Promise<boolean>',
    ]) {
      expect(kotelokSource).toContain(sig)
    }
  })

  test('unscoped CreateRoom is a top-level function', () => {
    expect(kotelokSource).toMatch(
      /export async function createRoom\(store: SyncStore/,
    )
  })

  test('root createApi collects state + actions', () => {
    expect(kotelokSource).toContain('export function createApi(store: SyncStore)')
    expect(kotelokSource).toContain('room: (id: string) => createGameRoomNode(store, id)')
    expect(kotelokSource).toContain('createRoom:')
  })

  test('field with @auth(read: "owner") preserves directive in JSDoc', () => {
    // v0.3: @auth is promoted to IDE-visible JSDoc rather than a bare
    // comment. The exact shape is `@auth read=owner` inside a /** */ block.
    expect(kotelokSource).toContain(`@auth read=owner`)
  })

  test('REALTIME sub-field preserves directive as comment', () => {
    expect(kotelokSource).toContain(`// @sync(qos: REALTIME)`)
  })

  test('collision-prone field `status` is renamed to $statusField on reactive side', () => {
    // RoomStatus-typed field `status` on GameRoom would collide with the facade's $status.
    expect(kotelokSource).toContain(`$statusField: ISyncNode<RoomStatus>`)
  })

  test('CRDT schema section is emitted with expected paths (FINDINGS §4.2)', () => {
    // The schema const is derived from @crdt / @sync directives. For the
    // fixture Kotelok SDL it must cover the scoped GameRoom fields and
    // recurse into Player / Team / RoundState children.
    expect(kotelokSource).toContain(`import type { FieldSchema } from `)
    expect(kotelokSource).toContain(`export const kotelokSchema: Record<string, FieldSchema>`)
    for (const path of [
      `'room.*.id': { type: 'lww' }`,
      `'room.*.players': { type: 'or-set' }`,
      `'room.*.players.*.id': { type: 'lww' }`,
      `'room.*.teams': { type: 'or-set' }`,
      `'room.*.wordSubmissions.*.count': { type: 'lww' }`,
    ]) {
      expect(kotelokSource).toContain(path)
    }
    // REALTIME field `timeLeft` is skipped, not silent — comment records the decision.
    expect(kotelokSource).toContain(`timeLeft — REALTIME`)
    // Record-level REALTIME records (SystemInfo) contribute nothing.
    expect(kotelokSource).not.toContain(`SystemInfo.online`)
    expect(kotelokSource).not.toContain(`systemInfo.online`)
  })
})

describe('Kotelok snapshot', () => {
  test('matches stored snapshot byte-for-byte', () => {
    if (!existsSync(SNAPSHOT)) {
      writeFileSync(SNAPSHOT, kotelokSource)
      // First run: create snapshot. Test passes.
      console.warn(`[snapshot] created ${SNAPSHOT}`)
      return
    }
    const stored = readFileSync(SNAPSHOT, 'utf8')
    if (stored !== kotelokSource) {
      // Easier diff surface for humans.
      const a = stored.split('\n')
      const b = kotelokSource.split('\n')
      const max = Math.max(a.length, b.length)
      for (let i = 0; i < max; i++) {
        if (a[i] !== b[i]) {
          console.error(`line ${i + 1}: expected ${JSON.stringify(a[i])}\n         got ${JSON.stringify(b[i])}`)
          break
        }
      }
    }
    expect(kotelokSource).toBe(stored)
  })
})

describe('core.identity namespace — scalars only', () => {
  test('emits type aliases for user scalars', () => {
    const res = compileSources(loadFixture())
    const gen = generate(res.ir!, { namespace: 'core.identity' })
    const src = gen.files[0].content
    expect(src).toContain('export type UUID = string')
    expect(src).toContain('export type DeviceID = string')
  })
})
