// @alaq/graph-tauri — file header + assembly helpers.

import { LineBuffer } from './utils'
// `_version.ts` is a build artifact synced from `package.yaml` by
// `alak/scripts/sync-generator-versions.ts`. Regenerated on every
// `bun run build:types` via the `prebuild:types` hook.
export { GENERATOR_NAME, GENERATOR_VERSION } from './_version'
import { GENERATOR_NAME, GENERATOR_VERSION } from './_version'

export interface HeaderOptions {
  namespace: string
  schemaVersion: number
  pluginImport: string
  header: boolean
}

/**
 * Emit the standard "AUTOGENERATED" banner + imports. Banner is suppressed
 * when `header: false` (useful for snapshot diffs or inlining).
 *
 * The only runtime import is Tauri v2's `invoke`. v0.1 of this generator is
 * plain: no nucl, no `@alaq/plugin-tauri` wrapping, no events, no state.
 */
export function emitHeader(buf: LineBuffer, opts: HeaderOptions) {
  if (opts.header) {
    buf.line(`// AUTOGENERATED by ${GENERATOR_NAME} v${GENERATOR_VERSION}`)
    buf.line(`// Schema: ${opts.namespace} v${opts.schemaVersion}`)
    buf.line(`// DO NOT EDIT — regenerate from .aql sources`)
    buf.blank()
  }
  buf.line(`import { invoke } from '${opts.pluginImport}'`)
  buf.blank()
}

/**
 * Prepend a section divider comment. Purely cosmetic — makes the output
 * easier to skim.
 */
export function emitSection(buf: LineBuffer, title: string) {
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.line(`// ${title}`)
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.blank()
}
