// @alaq/graph-tauri — public entry point.
//
// Reads an IR produced by `@alaq/graph` and emits TypeScript code with
// plain typed wrappers over Tauri v2's `invoke`. One self-contained `.ts`
// file per namespace.
//
// What v0.1 covers:
//   • enums                  — TS `enum` per SDL enum
//   • record interfaces      — `I<Record>` (readonly fields)
//   • action input types     — `I<Action>Input`
//   • action wrappers        — plain `async function <camelName>(input): Promise<Out>`
//   • root API               — `createTauriApi()` collecting every wrapper
//   • events + state         — STUBS (placeholder export + warning)
//
// What it explicitly does NOT do:
//   • nucl-wrapped reactive atoms
//   • event listeners (blocked on IR P.1 leadingComments)
//   • tree-shaking hints for transport (`@local`, `@transport`, etc.)
//
// Kept symmetric with `@alaq/graph-link-state` (same utility names, same
// header shape) so a consumer switching between the two targets has no
// mental overhead.

import type {
  IR,
  IRAction,
  IRRecord,
  IRSchema,
} from '@alaq/graph'

import {
  GENERATOR_NAME,
  GENERATOR_VERSION,
  emitHeader,
  emitSection,
} from './emit'
import { emitEnums } from './enums-gen'
import {
  emitRecordInterfaces,
  emitActionInputInterfaces,
  emitEventInterfaces,
} from './types-gen'
import { emitActions } from './actions-gen'
import { emitApi } from './api-gen'
import { emitEventsStub } from './events-gen'
import { emitStateStub } from './state-gen'
import { LineBuffer, buildTypeContext } from './utils'

// ────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────

export interface GenerateOptions {
  /** Target one namespace. When omitted, every namespace in the IR is emitted. */
  namespace?: string
  /**
   * Emit the AUTOGENERATED banner at the top of each file.
   * Default: true.
   */
  header?: boolean
  /**
   * Module specifier the generated file imports `invoke` from.
   * Default: '@tauri-apps/api/core' — at the time of v0.1 writing,
   * `@alaq/plugin-tauri` does not re-export `invoke` under an `/ipc` subpath
   * (confirmed against packages/plugin-tauri/src/index.ts + package.yaml:
   * only `tauriPlugin`, `createRealIPC`, `hasTauri`, `createFakeIPC` are
   * exported). Callers can override this if they later add such a re-export
   * or want to swap in a custom invoke proxy for tests.
   */
  pluginImport?: string
}

export interface GenerateDiagnostic {
  severity: 'error' | 'warning'
  message: string
}

export interface GenerateFile {
  path: string
  content: string
}

export interface GenerateResult {
  files: GenerateFile[]
  diagnostics: GenerateDiagnostic[]
}

const DEFAULTS: Required<Omit<GenerateOptions, 'namespace'>> = {
  header: true,
  pluginImport: '@tauri-apps/api/core',
}

/**
 * v0.3.4 (W8), tightened v0.3.5 (C7): transport kinds this generator emits
 * code for. Compared against `IRSchema.transport` (projected from
 * `@transport(kind: "...")`, SPEC §7.14). Mismatch → E025 error, generator
 * returns `files: []`. `"any"` is always compatible — schemas without
 * `@transport` are treated as `"any"` per R222.
 */
const SUPPORTED_TRANSPORTS: ReadonlyArray<string> = ['tauri', 'any']

/**
 * Transform an IR into TypeScript source files. Pure function: no FS,
 * no network, deterministic for a given IR + options. The caller decides
 * where to write `files[*].path`.
 */
export function generate(
  ir: IR,
  options: GenerateOptions = {},
): GenerateResult {
  const opts = { ...DEFAULTS, ...options }
  const files: GenerateFile[] = []
  const diagnostics: GenerateDiagnostic[] = []

  const namespaces = options.namespace
    ? [options.namespace]
    : Object.keys(ir.schemas).sort()

  for (const ns of namespaces) {
    const schema = ir.schemas[ns]
    if (!schema) {
      diagnostics.push({
        severity: 'error',
        message: `Namespace "${ns}" not found in IR.`,
      })
      continue
    }

    // v0.3.4 (W8), tightened v0.3.5 (C7): E025 on @transport mismatch —
    // generator refuses emission (SPEC §7.14 R221/R224). Unset / "any"
    // suppress per R222.
    if (schema.transport && !SUPPORTED_TRANSPORTS.includes(schema.transport)) {
      diagnostics.push({
        severity: 'error',
        message:
          `schema "${schema.namespace}" declares @transport(kind: "${schema.transport}") ` +
          `which is outside @alaq/graph-tauri supported transports [${SUPPORTED_TRANSPORTS.join(', ')}]; ` +
          `generation refused (E025). Set @transport(kind: "any") or omit the directive to opt out.`,
      })
      return { files: [], diagnostics }
    }

    const content = generateNamespace(schema, opts, diagnostics)

    // Namespaces like "belladonna.reader" contain dots. The recon spec asked
    // for a "flat" filename for the Tauri target — dots replaced with `.`
    // already work on every OS/bundler, so we keep them and only add the
    // `.tauri.generated.ts` suffix to mark the generator.
    const flat = schema.namespace
    files.push({
      path: `${flat}.tauri.generated.ts`,
      content,
    })
  }

  return { files, diagnostics }
}

/** v0.3.4 (W8): exported so tests/tooling can read the supported set. */
export { SUPPORTED_TRANSPORTS }

// ────────────────────────────────────────────────────────────────
// Namespace emitter
// ────────────────────────────────────────────────────────────────

function generateNamespace(
  schema: IRSchema,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
  diagnostics: GenerateDiagnostic[],
): string {
  const buf = new LineBuffer()
  emitHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    pluginImport: opts.pluginImport,
    header: opts.header,
  })

  const ctx = buildTypeContext(schema)

  // ── Enums ──
  if (Object.keys(schema.enums).length > 0) {
    emitSection(buf, 'Enums')
    emitEnums(buf, schema.enums)
  }

  // ── User scalars ──
  if (Object.keys(schema.scalars).length > 0) {
    emitSection(buf, 'Scalars (user-defined, opaque strings)')
    const names = Object.keys(schema.scalars).sort()
    for (const name of names) {
      buf.line(`export type ${name} = string`)
    }
    buf.blank()
  }

  // ── Record interfaces ──
  if (Object.keys(schema.records).length > 0) {
    emitSection(buf, 'Record value interfaces')
    emitRecordInterfaces(buf, schema.records, ctx)
  }

  // ── Event payload interfaces (v0.3.4 / W9) ──
  if (Object.keys(schema.events).length > 0) {
    emitSection(buf, 'Event payload interfaces')
    emitEventInterfaces(buf, schema.events, ctx)
  }

  // ── Action Input interfaces ──
  if (Object.keys(schema.actions).length > 0) {
    emitSection(buf, 'Action input types')
    emitActionInputInterfaces(buf, schema.actions, ctx)
  }

  // ── Action wrappers (plain typed invoke) ──
  if (Object.keys(schema.actions).length > 0) {
    emitSection(buf, 'Action wrappers (plain invoke)')
    emitActions(buf, schema.actions, ctx)
  }

  // ── Root API ──
  if (Object.keys(schema.actions).length > 0) {
    emitSection(buf, 'Root API')
    emitApi(buf, schema.actions)
  }

  // ── Events (stub) ──
  emitSection(buf, 'Events (STUB in v0.1)')
  emitEventsStub(buf, schema, diagnostics)

  // ── State (stub) ──
  emitSection(buf, 'State (STUB in v0.1)')
  emitStateStub(buf, schema, diagnostics)

  // ── Opaque streams — acknowledged, not supported ──
  const opaques = schema.opaques ?? {}
  if (Object.keys(opaques).length > 0) {
    for (const name of Object.keys(opaques).sort()) {
      diagnostics.push({
        severity: 'warning',
        message: `Opaque stream "${name}" is not supported by @alaq/graph-tauri v0.1.`,
      })
    }
  }

  return buf.toString()
}

// Re-export package constants for testing + consumer assertions.
export { GENERATOR_NAME, GENERATOR_VERSION }

// Re-export graph types so downstream generators-of-generators can type
// their IR arguments from a single import site (same convention as the
// sibling graph-link-state package).
export type { IR, IRSchema, IRRecord, IRAction } from '@alaq/graph'
