// @alaq/graph-zenoh — file header, section dividers and Cargo manifest block.

import { LineBuffer } from './utils'

export const GENERATOR_NAME = '@alaq/graph-zenoh'
export const GENERATOR_VERSION = '0.1.0-draft'

export interface HeaderOptions {
  namespace: string
  schemaVersion: number
  zenohVersion: string
  needsCbor: boolean
  needsAutomerge: boolean
  header: boolean
}

/**
 * Emit the AUTOGENERATED banner plus `use` imports. When `header: false`,
 * the banner is suppressed but the imports are still emitted — the output
 * must always be a valid Rust module.
 */
export function emitHeader(buf: LineBuffer, opts: HeaderOptions) {
  if (opts.header) {
    buf.line(`// AUTOGENERATED by ${GENERATOR_NAME} v${GENERATOR_VERSION}`)
    buf.line(`// Schema: ${opts.namespace} v${opts.schemaVersion}`)
    buf.line(`// DO NOT EDIT — regenerate from .aql sources`)
    buf.line(`//`)
    buf.line(`// Required Cargo dependencies:`)
    buf.line(`//   zenoh = "${opts.zenohVersion}"`)
    buf.line(`//   serde = { version = "1", features = ["derive"] }`)
    buf.line(`//   serde_json = "1"`)
    if (opts.needsCbor) {
      buf.line(`//   serde_cbor = "0.11"   # for @atomic records`)
    }
    if (opts.needsAutomerge) {
      buf.line(`//   automerge = "0.6"     # for @crdt records`)
    }
    buf.blank()
  }
  buf.line(`#![allow(dead_code, unused_imports, clippy::all)]`)
  buf.blank()
  buf.line(`use serde::{Serialize, Deserialize};`)
  buf.line(`use zenoh::{Session, prelude::r#async::*};`)
  buf.line(`use std::sync::Arc;`)
  if (opts.needsCbor) {
    buf.line(`use serde_cbor;`)
  }
  buf.blank()
}

/**
 * Emit a section divider comment. Purely cosmetic.
 */
export function emitSection(buf: LineBuffer, title: string) {
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.line(`// ${title}`)
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.blank()
}

/**
 * Emit the suggested Cargo.toml block at the bottom of the file as a block
 * comment. This is documentation — downstream projects copy these lines into
 * their own Cargo.toml to satisfy the generated code.
 */
export function emitCargoFooter(
  buf: LineBuffer,
  opts: { zenohVersion: string; needsCbor: boolean; needsAutomerge: boolean },
) {
  buf.line(`/*`)
  buf.line(` * Suggested Cargo.toml fragment:`)
  buf.line(` *`)
  buf.line(` * [dependencies]`)
  buf.line(` * zenoh = "${opts.zenohVersion}"`)
  buf.line(` * serde = { version = "1", features = ["derive"] }`)
  buf.line(` * serde_json = "1"`)
  buf.line(` * tokio = { version = "1", features = ["full"] }`)
  if (opts.needsCbor) {
    buf.line(` * serde_cbor = "0.11"`)
  }
  if (opts.needsAutomerge) {
    buf.line(` * automerge = "0.6"`)
  }
  buf.line(` */`)
}
