// @alaq/graph-zenoh — public entry point.
//
// Reads an IR produced by `@alaq/graph` and emits a single-file Rust module
// per namespace. The output contains:
//
//   1. Banner + `use` imports
//   2. `pub mod topics` — schema-level topic constants
//   3. User-defined scalars as `pub type X = String;`
//   4. Enums with `#[serde(rename_all = "SCREAMING_SNAKE_CASE")]`
//   5. Record structs (`#[derive(Serialize, Deserialize)]`) + impl blocks for
//      `@scope`, `@crdt`, `@atomic`
//   6. Per-record `publish_` / `subscribe_` helpers over `zenoh::Session`
//   7. Per-action request/reply helpers (`call_<action>`)
//   8. Opaque streams — TODO comments + warnings
//   9. Cargo.toml suggestion in a trailing block comment
//
// Wire mapping is normative per SPEC §11 for default-target implementations.
// v0.1 aims for a valid Rust module with the right topic shapes. Byte-level
// wire-parity with Sokol-Bus is deferred.

import type {
  IR,
  IRAction,
  IROpaque,
  IRRecord,
  IRSchema,
} from '@alaq/graph'
import {
  GENERATOR_NAME,
  GENERATOR_VERSION,
  emitCargoFooter,
  emitHeader,
  emitSection,
} from './emit'
import { emitActions } from './actions-gen'
import { emitAllCrdtDocEvents, hasAnyCrdtDocEvents } from './events-gen'
import { emitAllLiveliness, hasAnyLiveliness } from './liveliness-gen'
import { emitAllPubSub, emitCompositePubSub } from './publishers-gen'
import { emitCrdtDocWrappers, emitEnums, emitRecords, emitUserScalars } from './types-gen'
import { emitTopicsModule } from './topics-gen'
import { LineBuffer, buildTypeContext, hasDirective } from './utils'

// ────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────

export interface GenerateOptions {
  /** Target one namespace. When omitted, every namespace in the IR is emitted. */
  namespace?: string
  /** Emit the AUTOGENERATED banner + Cargo-deps header comment. Default true. */
  header?: boolean
  /** Target zenoh crate version (for header-comment dep list). Default "0.11". */
  zenohVersion?: string
  /** Emit Automerge-flavored helpers for `@crdt` records. Default true (stubs only in v0.1). */
  automerge?: boolean
  /** Emit serde_cbor encode/decode helpers for `@atomic` records. Default true. */
  cbor?: boolean
}

export interface GenerateDiagnostic {
  severity: 'error' | 'warning'
  message: string
}

export interface GenerateFile {
  path: string
  content: string
}

export interface GenerateResult {
  files: GenerateFile[]
  diagnostics: GenerateDiagnostic[]
}

const DEFAULTS: Required<Omit<GenerateOptions, 'namespace'>> = {
  header: true,
  zenohVersion: '0.11',
  automerge: true,
  cbor: true,
}

/**
 * v0.3.4 (W8), tightened v0.3.5 (C7): transport kinds this generator emits
 * code for. Compared against `IRSchema.transport` (projected from
 * `@transport(kind: "...")`, SPEC §7.14). Mismatch → E025 error, generator
 * returns `files: []`. `"any"` is always compatible — schemas without
 * `@transport` are treated as `"any"` per R222.
 */
const SUPPORTED_TRANSPORTS: ReadonlyArray<string> = ['zenoh', 'any']

/**
 * Transform an IR into Rust source files. Pure function: no FS, no network,
 * deterministic for a given IR + options. The caller decides where to write
 * `files[*].path`.
 */
export function generate(ir: IR, options: GenerateOptions = {}): GenerateResult {
  const opts = { ...DEFAULTS, ...options }
  const files: GenerateFile[] = []
  const diagnostics: GenerateDiagnostic[] = []

  const namespaces = options.namespace
    ? [options.namespace]
    : Object.keys(ir.schemas).sort()

  for (const ns of namespaces) {
    const schema = ir.schemas[ns]
    if (!schema) {
      diagnostics.push({
        severity: 'error',
        message: `Namespace "${ns}" not found in IR.`,
      })
      continue
    }

    // v0.3.4 (W8), tightened v0.3.5 (C7): E025 on @transport mismatch —
    // generator refuses emission (SPEC §7.14 R221/R224). Unset / "any"
    // suppress per R222.
    if (schema.transport && !SUPPORTED_TRANSPORTS.includes(schema.transport)) {
      diagnostics.push({
        severity: 'error',
        message:
          `schema "${schema.namespace}" declares @transport(kind: "${schema.transport}") ` +
          `which is outside @alaq/graph-zenoh supported transports [${SUPPORTED_TRANSPORTS.join(', ')}]; ` +
          `generation refused (E025). Set @transport(kind: "any") or omit the directive to opt out.`,
      })
      return { files: [], diagnostics }
    }

    const content = generateNamespace(schema, opts, diagnostics)
    // Filesystem-friendly module name: dots in namespaces (e.g. core.identity)
    // become underscores for the Rust path. The caller may override by writing
    // a different filename.
    const safeBase = schema.namespace.replace(/[^a-zA-Z0-9_]/g, '_')
    files.push({ path: `${safeBase}.rs`, content })
  }

  return { files, diagnostics }
}

/** v0.3.4 (W8): exported so tests/tooling can read the supported set. */
export { SUPPORTED_TRANSPORTS }

// ────────────────────────────────────────────────────────────────
// Namespace emitter
// ────────────────────────────────────────────────────────────────

function generateNamespace(
  schema: IRSchema,
  opts: Required<Omit<GenerateOptions, 'namespace'>>,
  diagnostics: GenerateDiagnostic[],
): string {
  const buf = new LineBuffer()
  const ctx = buildTypeContext(schema)

  // Scan directives once to decide which imports we need.
  const { needsCbor, needsAutomerge, needsComposite } = scanFeatureFlags(schema)

  emitHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    zenohVersion: opts.zenohVersion,
    needsCbor: needsCbor && opts.cbor,
    needsAutomerge: needsAutomerge && opts.automerge,
    needsComposite,
    header: opts.header,
  })

  // ── Topic module ──
  emitSection(buf, 'Topic prefixes')
  emitTopicsModule(buf, schema)

  // ── User scalars ──
  if (Object.keys(schema.scalars).length > 0) {
    emitSection(buf, 'Scalars (user-defined, opaque strings)')
    emitUserScalars(buf, schema.scalars)
  }

  // ── Enums ──
  if (Object.keys(schema.enums).length > 0) {
    emitSection(buf, 'Enums')
    emitEnums(buf, schema.enums)
  }

  // ── Records (struct + impl) ──
  if (Object.keys(schema.records).length > 0) {
    emitSection(buf, 'Records — structs and impl blocks')
    emitRecords(buf, schema.records, ctx, schema.namespace, diagnostics)
  }

  // ── Composite CRDT document wrappers (v0.3.6, SPEC §7.15–§7.17) ──
  if (needsComposite) {
    emitSection(buf, 'Composite CRDT document wrappers')
    emitCrdtDocWrappers(buf, schema, diagnostics)
  }

  // ── Publisher / Subscriber helpers ──
  if (Object.keys(schema.records).length > 0) {
    emitSection(buf, 'Publish / Subscribe helpers')
    emitAllPubSub(buf, schema.records)
  }

  // ── Composite document pub/sub helpers ──
  if (needsComposite) {
    emitSection(buf, 'Publish / Subscribe helpers — composite CRDT documents')
    emitCompositePubSub(buf, schema, diagnostics)
  }

  // ── Composite document SyncEvent + emit_*_diffs (v0.3.11, SPEC §7.15+) ──
  if (needsComposite && hasAnyCrdtDocEvents(schema)) {
    emitSection(buf, 'Composite CRDT document events (SyncEvent + emit_*_diffs)')
    emitAllCrdtDocEvents(buf, schema, diagnostics)
  }

  // ── Zenoh liveliness presence helpers (v0.3.10, SPEC §7.26) ──
  if (hasAnyLiveliness(schema.records)) {
    emitSection(buf, 'Liveliness presence helpers (@liveliness_token)')
    emitAllLiveliness(buf, schema.records)
  }

  // ── Actions ──
  if (Object.keys(schema.actions).length > 0) {
    emitSection(buf, 'Actions (request/reply + fire-forget)')
    emitActions(buf, schema.actions, ctx)
  }

  // ── Opaque streams (TODO) ──
  const opaques = schema.opaques ?? {}
  if (Object.keys(opaques).length > 0) {
    emitSection(buf, 'Opaque streams (TODO: runtime support pending)')
    for (const name of Object.keys(opaques).sort()) {
      const o: IROpaque = opaques[name]
      buf.line(
        `// TODO: opaque stream ${o.name} (qos=${o.qos}${o.maxSize ? `, max_size=${o.maxSize}` : ''})`,
      )
      buf.line(`// Planned topic: "${schema.namespace}/stream/${o.name}"`)
      diagnostics.push({
        severity: 'warning',
        message: `Opaque stream "${o.name}" is not yet supported by @alaq/graph-zenoh (emitted as TODO comment).`,
      })
    }
    buf.blank()
  }

  // ── Advisory warnings for directives we preserve but don't fully implement ──
  collectAdvisoryWarnings(schema, diagnostics)

  // ── Cargo footer ──
  emitCargoFooter(buf, {
    zenohVersion: opts.zenohVersion,
    needsCbor: needsCbor && opts.cbor,
    needsAutomerge: needsAutomerge && opts.automerge,
    needsComposite,
  })

  return buf.toString()
}

// ────────────────────────────────────────────────────────────────
// Feature-flag scan: which conditional imports do we need?
// ────────────────────────────────────────────────────────────────

function scanFeatureFlags(schema: IRSchema): {
  needsCbor: boolean
  needsAutomerge: boolean
  needsComposite: boolean
} {
  let needsCbor = false
  let needsAutomerge = false
  let needsComposite = false
  // Composite CRDT documents (v0.3.6 SPEC §7.15–§7.17) pull in both the
  // Automerge dep and the `alaq-graph-zenoh-rt` bridge.
  const schemaDirs = schema.directives ?? []
  if (schemaDirs.some(d => d.name === 'crdt_doc_topic')) {
    needsAutomerge = true
    needsComposite = true
  }
  for (const rec of Object.values(schema.records)) {
    if (hasDirective(rec.directives, 'atomic')) needsCbor = true
    if (hasDirective(rec.directives, 'crdt')) needsAutomerge = true
    if (hasDirective(rec.directives, 'crdt_doc_member')) {
      needsAutomerge = true
      needsComposite = true
    }
    // `Any` in any field forces serde_cbor into the dep list.
    for (const f of rec.fields) {
      if (hasDirective(f.directives, 'atomic')) needsCbor = true
      if (hasDirective(f.directives, 'crdt')) needsAutomerge = true
      if (fieldMentionsAny(f)) needsCbor = true
    }
  }
  return { needsCbor, needsAutomerge, needsComposite }
}

// Walk an IRField's type tree and look for `Any`. Covers bare `Any`, lists
// containing Any (the validator already rejects these — E026 — but the
// scanner must be tolerant of pre-validator IR so snapshot tests read
// cleanly), and Map values of Any (the permitted position).
function fieldMentionsAny(f: {
  type: string
  map?: boolean
  mapKey?: { type: string; map?: boolean; mapValue?: unknown }
  mapValue?: { type: string; map?: boolean; mapValue?: unknown }
}): boolean {
  if (f.type === 'Any') return true
  if (f.map && f.mapValue) {
    return refMentionsAny(f.mapValue as { type: string; map?: boolean; mapValue?: unknown })
  }
  return false
}

function refMentionsAny(ref: {
  type: string
  map?: boolean
  mapValue?: unknown
}): boolean {
  if (ref.type === 'Any') return true
  if (ref.map && ref.mapValue) {
    return refMentionsAny(ref.mapValue as { type: string; map?: boolean; mapValue?: unknown })
  }
  return false
}

// ────────────────────────────────────────────────────────────────
// Advisory warnings for preserved-but-not-implemented directives
// ────────────────────────────────────────────────────────────────

function collectAdvisoryWarnings(
  schema: IRSchema,
  diagnostics: GenerateDiagnostic[],
) {
  const passThroughSeen = new Set<string>()
  // v0.1 preserves these as comments only; runtime impl is downstream's job.
  const ignored = new Set(['auth', 'store', 'liveness', 'range', 'deprecated', 'added'])

  const scan = (dirs: { name: string }[] | undefined) => {
    if (!dirs) return
    for (const d of dirs) {
      if (ignored.has(d.name) && !passThroughSeen.has(d.name)) {
        passThroughSeen.add(d.name)
        diagnostics.push({
          severity: 'warning',
          message: `Directive @${d.name} is preserved as a comment only in v0.1 of @alaq/graph-zenoh.`,
        })
      }
    }
  }

  for (const rec of Object.values(schema.records)) {
    scan(rec.directives)
    for (const f of rec.fields) {
      scan(f.directives)
      // SPEC §7.23 / W009 (codegen completed v0.3.10): emit the
      // advisory at generation time so build-script consumers see it.
      // The struct field has been annotated with `#[deprecated]` in
      // types-gen.ts; this surface raises the same signal at the
      // generator-diagnostic level.
      const dep = (f.directives ?? []).find(d => d.name === 'deprecated_field')
      if (dep) {
        const rep = typeof dep.args?.replaced_by === 'string'
          ? (dep.args.replaced_by as string)
          : null
        diagnostics.push({
          severity: 'warning',
          message:
            `[W009] field "${rec.name}.${f.name}" is @deprecated_field` +
            (rep ? ` (replaced by "${rep}")` : '') +
            `; consumers should migrate before next major bump`,
        })
      }
    }
  }
  for (const a of Object.values(schema.actions)) {
    scan(a.directives)
    for (const f of a.input ?? []) scan(f.directives)
  }
}

// Re-export generator identity for caller assertions.
export { GENERATOR_NAME, GENERATOR_VERSION }
export type { IR, IRSchema, IRRecord, IRAction } from '@alaq/graph'
