name: "@alaq/queue"
version: 6.0.0-alpha.0
description: High-performance reactive Job Scheduler for Alak ecosystem
type: module
main: ./src/index.ts
types: ./dist/index.d.ts
keywords:
  - queue
  - job scheduler
  - priority queue
  - concurrency
  - reactive
  - quark
dependencies:
  "@alaq/quark": 6.0.0-alpha.0
publishConfig:
  access: public
