name: "@alaq/queue"
version: "6.0.0-alpha.0"
description: High-performance reactive Job Scheduler for Alak ecosystem
homepage: https://github.com/carabins/alaq/package/queue
keywords:
  - queue
  - job scheduler
  - priority queue
  - concurrency
  - reactive
  - quark
dependencies:
  "@alaq/quark": alpha
