// AUTOGENERATED by @alaq/graph-zenoh v0.1.0-draft
// Schema: valkyrie v1
// DO NOT EDIT — regenerate from .aql sources
//
// Required Cargo dependencies:
//   serde = { version = "1", features = ["derive"] }
//   serde_json = "1"
//   serde_cbor = "0.11"   # for @atomic records and Any fields
//   automerge = "=0.6.0"  # pinned — matches composite CRDT wire format
//   alaq-graph-zenoh-rt = { path = "../alaq-graph-zenoh-rt" }
//     # composite CRDT document runtime (CrdtDoc bridge)

#![allow(dead_code, unused_imports, clippy::all)]

use serde::{Serialize, Deserialize};
use serde_cbor;
use alaq_graph_zenoh_rt::CrdtDoc;

// ────────────────────────────────────────────────────────────────
// Topic prefixes
// ────────────────────────────────────────────────────────────────

pub mod topics {
    //! Compile-time topic-prefix constants derived from the SDL schema.
    //! Per-record and per-action helpers live on the type themselves.

    /// Schema namespace (topic root).
    pub const NAMESPACE: &'static str = "valkyrie";
    /// Prefix for unscoped actions: "{namespace}/action".
    pub const ACTION_PREFIX: &'static str = "valkyrie/action";
    /// Prefix for opaque streams: "{namespace}/stream".
    pub const OPAQUE_PREFIX: &'static str = "valkyrie/stream";
}

// ────────────────────────────────────────────────────────────────
// Enums
// ────────────────────────────────────────────────────────────────

// SDL: enum DeviceRole { VALKYRIE, KLADINETS, SOKOL, NIGHT_WATCH }
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum DeviceRole {
    Valkyrie,
    Kladinets,
    Sokol,
    NightWatch,
}

// SDL: enum PointKind { TARGET, OBSERVATION, GROUP_POSITION, GROUND_STATION }
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum PointKind {
    Target,
    Observation,
    GroupPosition,
    GroundStation,
}

// ────────────────────────────────────────────────────────────────
// Records — structs and impl blocks
// ────────────────────────────────────────────────────────────────

// SDL: record DeviceEntry @crdt_doc_member(doc: "GroupSync", map: "devices", lww_field: "ts") @breaking_change(reason: "Busynca Phase-0 wire contract — devices are hard-deleted (models.rs:67-81). Migrating to soft_delete is a wire break for live peers.") @crdt(type: LWW_MAP, key: "ts")
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeviceEntry {
    pub device_id: String,
    pub name: String,
    pub nickname: Option<String>,
    pub role: DeviceRole,
    pub subtype: Option<String>,
    pub ts: i64,
}

// SDL: record PositionMsg @atomic @topic(pattern: "valkyrie/{group}/device/{id}/position")
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PositionMsg {
    pub device_id: String,
    pub ts: i64,
    pub lat: f64,
    pub lon: f64,
    pub altitude: Option<f64>,
    pub heading: Option<f64>,
    pub speed: Option<f64>,
    pub accuracy_m: Option<f32>,
}

// SDL: record StatusMsg @atomic @topic(pattern: "valkyrie/{group}/device/{id}/status")
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StatusMsg {
    pub device_id: String,
    pub ts: i64,
    pub battery: Option<f32>,
    pub signal: Option<f32>,
    pub online: bool,
}

// SDL: record SyncPoint @crdt_doc_member(doc: "GroupSync", map: "points", lww_field: "updated_at", soft_delete: {"flag":"is_deleted","ts_field":"updated_at"}) @crdt(type: LWW_MAP, key: "updated_at")
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncPoint {
    pub id: String,
    pub group: String,
    pub kind: PointKind,
    pub lat: f64,
    pub lon: f64,
    pub altitude: Option<f64>,
    pub heading: Option<f64>,
    pub speed: Option<f64>,
    pub label: Option<String>,
    pub subtype: Option<String>,
    pub confidence: Option<f32>,
    pub author: String,
    pub created_at: i64,
    pub updated_at: i64,
    pub parent_id: Option<String>,
    pub is_deleted: bool,
    pub extras: std::collections::BTreeMap<String, serde_cbor::Value>,
}

impl DeviceEntry {
    /// @crdt_doc_member — entries of this record are stored inside
    /// a composite Automerge document; see the matching `<Doc>Doc`
    /// wrapper for publish/subscribe and per-entry upsert/delete/list.

    /// CRDT type declared in SDL (@crdt).
    pub fn crdt_type() -> &'static str { "LWW_MAP" }

    /// LWW resolution key — used by the enclosing `<Doc>Doc` wrapper
    /// to pick the winner on merge. Read from the `ts` field.
    pub fn lww_key(&self) -> i64 {
        self.ts
    }

}

impl PositionMsg {
    /// Custom @topic(pattern: "...") — no placeholder substitution in v0.1.
    pub const TOPIC_PATTERN: &'static str = "valkyrie/{group}/device/{id}/position";

    /// @atomic — encoded as an opaque CBOR blob on the wire.
    pub fn encode_cbor(&self) -> Result<Vec<u8>, serde_cbor::Error> {
        serde_cbor::to_vec(self)
    }

    pub fn decode_cbor(bytes: &[u8]) -> Result<Self, serde_cbor::Error> {
        serde_cbor::from_slice(bytes)
    }

}

impl StatusMsg {
    /// Custom @topic(pattern: "...") — no placeholder substitution in v0.1.
    pub const TOPIC_PATTERN: &'static str = "valkyrie/{group}/device/{id}/status";

    /// @atomic — encoded as an opaque CBOR blob on the wire.
    pub fn encode_cbor(&self) -> Result<Vec<u8>, serde_cbor::Error> {
        serde_cbor::to_vec(self)
    }

    pub fn decode_cbor(bytes: &[u8]) -> Result<Self, serde_cbor::Error> {
        serde_cbor::from_slice(bytes)
    }

}

impl SyncPoint {
    /// @crdt_doc_member — entries of this record are stored inside
    /// a composite Automerge document; see the matching `<Doc>Doc`
    /// wrapper for publish/subscribe and per-entry upsert/delete/list.

    /// CRDT type declared in SDL (@crdt).
    pub fn crdt_type() -> &'static str { "LWW_MAP" }

    /// LWW resolution key — used by the enclosing `<Doc>Doc` wrapper
    /// to pick the winner on merge. Read from the `updated_at` field.
    pub fn lww_key(&self) -> i64 {
        self.updated_at
    }

}

// ────────────────────────────────────────────────────────────────
// Composite CRDT document wrappers
// ────────────────────────────────────────────────────────────────

// SDL: @crdt_doc_topic(doc: "GroupSync", pattern: "valkyrie/{group}/sync/patch")
// SDL: @schema_version(doc: "GroupSync", value: 2)
pub struct GroupSyncDoc {
    inner: CrdtDoc,
}

impl GroupSyncDoc {
    /// Expected schema_version pinned into the Automerge document.
    pub const SCHEMA_VERSION: u32 = 2 as u32;

    /// Zenoh topic pattern from @crdt_doc_topic. Placeholder
    /// substitution is the caller's responsibility in v0.1.
    pub const TOPIC_PATTERN: &'static str = "valkyrie/{group}/sync/patch";

    /// Root-map names in this composite document. Pre-sorted
    /// ascending — the runtime caches its Automerge template
    /// blob on `(SCHEMA_VERSION, MAP_KEYS)`, so every replica
    /// MUST pass the same slice to keep merges wire-compatible.
    pub const MAP_KEYS: &'static [&'static str] = &["devices", "points"];

    /// Create a fresh, empty document pinned to `SCHEMA_VERSION`
    /// with every root map in `MAP_KEYS` pre-created.
    pub fn new() -> Self {
        Self { inner: CrdtDoc::new(Self::SCHEMA_VERSION, Self::MAP_KEYS) }
    }

    /// Load an existing Automerge blob. If the on-disk `schema_version`
    /// does not match `SCHEMA_VERSION` the document is dropped and
    /// re-initialised (SPEC §7.17 R251). The second tuple element is
    /// `true` when a rebuild happened — the caller MUST log this.
    /// `bytes` of `None` creates a fresh document; `Some` defers to
    /// `CrdtDoc::load_or_init` which handles the mismatch case.
    pub fn load_or_init(bytes: Option<&[u8]>) -> anyhow::Result<(Self, bool)> {
        match bytes {
            None => Ok((Self::new(), false)),
            Some(b) => {
                let (inner, rebuilt) = CrdtDoc::load_or_init(b, Self::SCHEMA_VERSION, Self::MAP_KEYS)?;
                Ok((Self { inner }, rebuilt))
            }
        }
    }

    /// Serialize the whole document to an Automerge binary blob.
    pub fn save(&mut self) -> Vec<u8> {
        self.inner.save()
    }

    /// Merge a remote snapshot into this document (Automerge merge).
    pub fn merge_remote(&mut self, other: &[u8]) -> anyhow::Result<()> {
        self.inner.merge_remote(other)?;
        Ok(())
    }

    /// Insert or overwrite a `SyncPoint` entry under the
    /// `"points"` root map. LWW key: `updated_at`.
    pub fn upsert_points(&mut self, entry: &SyncPoint) -> anyhow::Result<()> {
        let json = serde_json::to_string(entry)?;
        let id = &entry.id;
        let lww: i64 = entry.updated_at;
        self.inner.upsert_json("points", id, &json, lww, "updated_at").map_err(Into::into)
    }

    /// Mark a `SyncPoint` entry as deleted via soft-delete:
    /// writes `is_deleted: true` + `updated_at: tombstone_ts` into the
    /// entry's JSON cell and bumps LWW to `tombstone_ts`.
    pub fn delete_points(&mut self, id: &str, tombstone_ts: i64) -> anyhow::Result<()> {
        let spec = alaq_graph_zenoh_rt::SoftDeleteSpec {
            flag: "is_deleted",
            ts_field: "updated_at",
        };
        self.inner.delete_entry("points", id, tombstone_ts, Some(spec)).map_err(Into::into)
    }

    /// List all non-deleted `SyncPoint` entries.
    /// Entries with `is_deleted == true` are skipped (soft-delete).
    pub fn list_points(&self) -> anyhow::Result<Vec<SyncPoint>> {
        let items = self.inner.list_json("points")?;
        items.into_iter()
            .map(|s| serde_json::from_str::<SyncPoint>(&s).map_err(Into::into))
            .filter(|r| match r { Ok(v) => !v.is_deleted, Err(_) => true })
            .collect()
    }

    /// Insert or overwrite a `DeviceEntry` entry under the
    /// `"devices"` root map. LWW key: `ts`.
    pub fn upsert_devices(&mut self, entry: &DeviceEntry) -> anyhow::Result<()> {
        let json = serde_json::to_string(entry)?;
        let id = &entry.device_id;
        let lww: i64 = entry.ts;
        self.inner.upsert_json("devices", id, &json, lww, "ts").map_err(Into::into)
    }

    /// Hard-delete a `DeviceEntry` entry (remove the Automerge cell).
    pub fn delete_devices(&mut self, id: &str, tombstone_ts: i64) -> anyhow::Result<()> {
        self.inner.delete_entry("devices", id, tombstone_ts, None).map_err(Into::into)
    }

    /// List all non-deleted `DeviceEntry` entries.
    pub fn list_devices(&self) -> anyhow::Result<Vec<DeviceEntry>> {
        let items = self.inner.list_json("devices")?;
        items.into_iter()
            .map(|s| serde_json::from_str::<DeviceEntry>(&s).map_err(Into::into))
            .collect()
    }

}

// ────────────────────────────────────────────────────────────────
// Composite CRDT document events (SyncEvent + emit_*_diffs)
// ────────────────────────────────────────────────────────────────

/// CRDT-document events for the `GroupSync` composite document.
/// Emitted by `emit_group_sync_*_diffs` and by
/// `GroupSyncDoc::merge_remote_with_events`.
/// Variants are derived from each `@crdt_doc_member` map key —
/// one `Upserted` and one `Deleted` per member record.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[non_exhaustive]
pub enum GroupSyncEvent {
    /// Upsert (insert or update) of a `DeviceEntry` entry
    /// in root map `"devices"`.
    DevicesUpserted(DeviceEntry),
    /// Removal of a `DeviceEntry` entry from root map
    /// `"devices"` — the payload is the entry id.
    DevicesDeleted(String),
    /// Upsert (insert or update) of a `SyncPoint` entry
    /// in root map `"points"`.
    PointsUpserted(SyncPoint),
    /// Removal of a `SyncPoint` entry from root map
    /// `"points"` — the payload is the entry id.
    PointsDeleted(String),
}

/// Diff two snapshots of root map `"devices"` and emit
/// `GroupSyncEvent::DevicesUpserted` / `DevicesDeleted` events
/// onto `tx`. An entry is "changed" when its `ts` value
/// differs between `before` and `after` — the same key the LWW
/// merge uses, so we never emit spurious upserts for unchanged
/// records. `broadcast::Sender::send` errors are dropped: a
/// dead receiver is the caller's contract, not ours.
pub fn emit_group_sync_devices_diffs(
    tx: &tokio::sync::broadcast::Sender<GroupSyncEvent>,
    before: &[DeviceEntry],
    after: &[DeviceEntry],
) {
    use std::collections::HashMap;
    let before_map: HashMap<&str, &DeviceEntry> =
        before.iter().map(|e| (e.device_id.as_str(), e)).collect();
    let after_map: HashMap<&str, &DeviceEntry> =
        after.iter().map(|e| (e.device_id.as_str(), e)).collect();

    for (id, entry) in &after_map {
        match before_map.get(id) {
            Some(prev) if prev.ts == entry.ts => {}
            _ => {
                let _ = tx.send(GroupSyncEvent::DevicesUpserted((*entry).clone()));
            }
        }
    }
    for id in before_map.keys() {
        if !after_map.contains_key(id) {
            let _ = tx.send(GroupSyncEvent::DevicesDeleted((*id).to_string()));
        }
    }
}

/// Diff two snapshots of root map `"points"` and emit
/// `GroupSyncEvent::PointsUpserted` / `PointsDeleted` events
/// onto `tx`. An entry is "changed" when its `updated_at` value
/// differs between `before` and `after` — the same key the LWW
/// merge uses, so we never emit spurious upserts for unchanged
/// records. `broadcast::Sender::send` errors are dropped: a
/// dead receiver is the caller's contract, not ours.
pub fn emit_group_sync_points_diffs(
    tx: &tokio::sync::broadcast::Sender<GroupSyncEvent>,
    before: &[SyncPoint],
    after: &[SyncPoint],
) {
    use std::collections::HashMap;
    let before_map: HashMap<&str, &SyncPoint> =
        before.iter().map(|e| (e.id.as_str(), e)).collect();
    let after_map: HashMap<&str, &SyncPoint> =
        after.iter().map(|e| (e.id.as_str(), e)).collect();

    for (id, entry) in &after_map {
        match before_map.get(id) {
            Some(prev) if prev.updated_at == entry.updated_at => {}
            _ => {
                let _ = tx.send(GroupSyncEvent::PointsUpserted((*entry).clone()));
            }
        }
    }
    for id in before_map.keys() {
        if !after_map.contains_key(id) {
            let _ = tx.send(GroupSyncEvent::PointsDeleted((*id).to_string()));
        }
    }
}

impl GroupSyncDoc {
    /// Merge a remote snapshot and emit per-map diff events on `tx`.
    /// Snapshots every member root-map before and after the merge,
    /// runs the underlying `merge_remote`, then fans out
    /// `GroupSyncEvent` events for entries that changed.
    ///
    /// Mirrors the `start_group_sync_listener` pattern in busynca's
    /// hand-written runtime: snapshot → merge → snapshot → diff →
    /// broadcast. Returning `anyhow::Result<()>` keeps the merge
    /// error path identical to plain `merge_remote`.
    pub fn merge_remote_with_events(
        &mut self,
        other: &[u8],
        tx: &tokio::sync::broadcast::Sender<GroupSyncEvent>,
    ) -> anyhow::Result<()> {
        // Snapshot every member root-map before the merge.
        let before_devices = self.list_devices().unwrap_or_default();
        let before_points = self.list_points().unwrap_or_default();

        // Run the underlying Automerge merge. Errors short-circuit;
        // nothing is emitted on failure (caller sees the error).
        self.merge_remote(other)?;

        // Snapshot after, then diff each member root-map.
        let after_devices = self.list_devices().unwrap_or_default();
        let after_points = self.list_points().unwrap_or_default();

        emit_group_sync_devices_diffs(tx, &before_devices, &after_devices);
        emit_group_sync_points_diffs(tx, &before_points, &after_points);

        Ok(())
    }
}

/*
 * Suggested Cargo.toml fragment:
 *
 * [dependencies]
 * serde = { version = "1", features = ["derive"] }
 * serde_json = "1"
 * serde_cbor = "0.11"
 * automerge = "=0.6.0"
 * alaq-graph-zenoh-rt = { path = "../alaq-graph-zenoh-rt" }
 * anyhow = "1"
 */
