// AUTOGENERATED by @alaq/graph-zenoh v0.1.0-draft
// Schema: sokol.v1 v1
// DO NOT EDIT — regenerate from .aql sources
//
// Required Cargo dependencies:
//   zenoh = "0.11"
//   serde = { version = "1", features = ["derive"] }
//   serde_json = "1"

#![allow(dead_code, unused_imports, clippy::all)]

use serde::{Serialize, Deserialize};
use zenoh::{Session, prelude::r#async::*};
use std::sync::Arc;

// ────────────────────────────────────────────────────────────────
// Topic prefixes
// ────────────────────────────────────────────────────────────────

pub mod topics {
    //! Compile-time topic-prefix constants derived from the SDL schema.
    //! Per-record and per-action helpers live on the type themselves.

    /// Schema namespace (topic root).
    pub const NAMESPACE: &'static str = "sokol.v1";
    /// Prefix for unscoped actions: "{namespace}/action".
    pub const ACTION_PREFIX: &'static str = "sokol.v1/action";
    /// Prefix for opaque streams: "{namespace}/stream".
    pub const OPAQUE_PREFIX: &'static str = "sokol.v1/stream";
}

// ────────────────────────────────────────────────────────────────
// Records — structs and impl blocks
// ────────────────────────────────────────────────────────────────

// SDL: record BortSysTelemetry @rename_case(kind: CAMEL) @topic(pattern: "sokol/v1/bort/{hw_id}/sys")
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BortSysTelemetry {
    pub hw_id: String,
    pub ts: i64,
    pub uptime_secs: i64,
    pub cpu: CpuInfo,
    pub memory: MemoryInfo,
    pub disk: DiskInfo,
    pub temperature: Option<f32>,
    pub load_avg: Vec<f32>,
    pub network: Vec<NetIface>,
    pub serial: SerialStatus,
    pub collectors: Vec<CollectorResult>,
}

// SDL: record CollectorResult @rename_case(kind: CAMEL)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CollectorResult {
    pub id: String,
    pub value: String,
    pub error: Option<String>,
}

// SDL: record CpuInfo @rename_case(kind: CAMEL)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CpuInfo {
    pub usage_percent: f32,
    pub core_count: i64,
}

// SDL: record DiskInfo @rename_case(kind: CAMEL)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DiskInfo {
    pub used_mb: i64,
    pub total_mb: i64,
    pub available_mb: i64,
}

// SDL: record GotoCmd @rename_case(kind: CAMEL) @topic(pattern: "sokol/v1/bort/{hw_id}/cmd/goto")
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GotoCmd {
    pub lat: f64,
    pub lon: f64,
    pub alt: f64,
    pub speed: f32,
    pub sender_id: String,
    pub ts: i64,
}

// SDL: record GotoCmdExtended @rename_case(kind: CAMEL) @topic(pattern: "sokol/v1/bort/{hw_id}/cmd/goto_ext")
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GotoCmdExtended {
    pub lat: f64,
    pub lon: f64,
    pub alt: f64,
    pub alt_frame: String,
    pub speed: f32,
    pub max_speed: bool,
    pub arrival_mode: String,
    pub loiter_radius: f32,
    pub sender_id: String,
    pub ts: i64,
}

// SDL: record GpsInjectCmd @rename_case(kind: CAMEL) @topic(pattern: "sokol/v1/bort/{hw_id}/cmd/gps_inject")
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GpsInjectCmd {
    pub lat: f64,
    pub lon: f64,
    pub alt: f64,
    pub fix_type: i64,
    pub gps_id: i64,
    pub satellites: i64,
    pub hdop: f32,
    pub vdop: f32,
    pub sender_id: String,
    pub ts: i64,
}

// SDL: record MemoryInfo @rename_case(kind: CAMEL)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MemoryInfo {
    pub used_mb: i64,
    pub total_mb: i64,
    pub available_mb: i64,
}

// SDL: record MeshModemNode @rename_case(kind: CAMEL)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MeshModemNode {
    pub id: i64,
    pub ip: String,
    pub snr: f64,
    pub rssi_ant1: f64,
    pub rssi_ant2: f64,
}

// SDL: record MeshModemStatus @rename_case(kind: CAMEL) @topic(pattern: "sokol/v1/mesh/{modem_id}/status")
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MeshModemStatus {
    pub modem_id: String,
    pub publisher_id: String,
    pub node_number: i64,
    pub nodes: Vec<MeshModemNode>,
    pub transmission_delay: Vec<TransmissionDelay>,
    pub temperature: f64,
    pub battery_voltage: f64,
    pub ts: i64,
}

// SDL: record NetIface @rename_case(kind: CAMEL)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NetIface {
    pub name: String,
    pub ip: String,
    pub up: bool,
}

// SDL: record SerialStatus @rename_case(kind: CAMEL)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SerialStatus {
    pub connected: bool,
    pub port: String,
    pub baud: i64,
    pub bytes_rx: i64,
    pub bytes_tx: i64,
    pub last_mavlink_ts: Option<i64>,
}

// SDL: record Telemetry @topic(pattern: "sokol/v1/bort/{hw_id}/tele")
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Telemetry {
    pub hw_id: String,
    pub display_id: String,
    pub ip: String,
    pub lat: f64,
    pub lon: f64,
    pub alt: f32,
    pub speed: f32,
    pub heading: f32,
    pub ts: i64,
    pub fc_connected: bool,
}

// SDL: record TransmissionDelay @rename_case(kind: CAMEL)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TransmissionDelay {
    pub target_node_id: i64,
    pub delay: i64,
    pub distance_km: f64,
}

impl BortSysTelemetry {
    /// Custom @topic(pattern: "...") — no placeholder substitution in v0.1.
    pub const TOPIC_PATTERN: &'static str = "sokol/v1/bort/{hw_id}/sys";

}

impl CollectorResult {
    /// Default unscoped topic: "{namespace}/CollectorResult".
    pub fn topic(namespace: &str) -> String {
        format!("{}/CollectorResult", namespace)
    }

}

impl CpuInfo {
    /// Default unscoped topic: "{namespace}/CpuInfo".
    pub fn topic(namespace: &str) -> String {
        format!("{}/CpuInfo", namespace)
    }

}

impl DiskInfo {
    /// Default unscoped topic: "{namespace}/DiskInfo".
    pub fn topic(namespace: &str) -> String {
        format!("{}/DiskInfo", namespace)
    }

}

impl GotoCmd {
    /// Custom @topic(pattern: "...") — no placeholder substitution in v0.1.
    pub const TOPIC_PATTERN: &'static str = "sokol/v1/bort/{hw_id}/cmd/goto";

}

impl GotoCmdExtended {
    /// Custom @topic(pattern: "...") — no placeholder substitution in v0.1.
    pub const TOPIC_PATTERN: &'static str = "sokol/v1/bort/{hw_id}/cmd/goto_ext";

}

impl GpsInjectCmd {
    /// Custom @topic(pattern: "...") — no placeholder substitution in v0.1.
    pub const TOPIC_PATTERN: &'static str = "sokol/v1/bort/{hw_id}/cmd/gps_inject";

}

impl MemoryInfo {
    /// Default unscoped topic: "{namespace}/MemoryInfo".
    pub fn topic(namespace: &str) -> String {
        format!("{}/MemoryInfo", namespace)
    }

}

impl MeshModemNode {
    /// Default unscoped topic: "{namespace}/MeshModemNode".
    pub fn topic(namespace: &str) -> String {
        format!("{}/MeshModemNode", namespace)
    }

}

impl MeshModemStatus {
    /// Custom @topic(pattern: "...") — no placeholder substitution in v0.1.
    pub const TOPIC_PATTERN: &'static str = "sokol/v1/mesh/{modem_id}/status";

}

impl NetIface {
    /// Default unscoped topic: "{namespace}/NetIface".
    pub fn topic(namespace: &str) -> String {
        format!("{}/NetIface", namespace)
    }

}

impl SerialStatus {
    /// Default unscoped topic: "{namespace}/SerialStatus".
    pub fn topic(namespace: &str) -> String {
        format!("{}/SerialStatus", namespace)
    }

}

impl Telemetry {
    /// Custom @topic(pattern: "...") — no placeholder substitution in v0.1.
    pub const TOPIC_PATTERN: &'static str = "sokol/v1/bort/{hw_id}/tele";

}

impl TransmissionDelay {
    /// Default unscoped topic: "{namespace}/TransmissionDelay".
    pub fn topic(namespace: &str) -> String {
        format!("{}/TransmissionDelay", namespace)
    }

}

// ────────────────────────────────────────────────────────────────
// Publish / Subscribe helpers
// ────────────────────────────────────────────────────────────────

/// Publish a `BortSysTelemetry` snapshot to `topic`.
/// The caller resolves `BortSysTelemetry::TOPIC_PATTERN` placeholders.
pub async fn publish_bort_sys_telemetry(
    session: &Session,
    topic: &str,
    value: &BortSysTelemetry,
) -> zenoh::Result<()> {
    let key = topic.to_string();
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to a pre-resolved `BortSysTelemetry` topic.
/// The caller resolves `BortSysTelemetry::TOPIC_PATTERN` placeholders.
pub async fn subscribe_bort_sys_telemetry<F>(
    session: Arc<Session>,
    topic: String,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(BortSysTelemetry) + Send + 'static,
{
    let key = topic.clone();
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<BortSysTelemetry>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `CollectorResult` snapshot to its unscoped zenoh topic.
pub async fn publish_collector_result(
    session: &Session,
    namespace: &str,
    value: &CollectorResult,
) -> zenoh::Result<()> {
    let key = CollectorResult::topic(namespace);
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to the unscoped `CollectorResult` topic and invoke `callback` on updates.
pub async fn subscribe_collector_result<F>(
    session: Arc<Session>,
    namespace: &str,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(CollectorResult) + Send + 'static,
{
    let key = CollectorResult::topic(namespace);
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<CollectorResult>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `CpuInfo` snapshot to its unscoped zenoh topic.
pub async fn publish_cpu_info(
    session: &Session,
    namespace: &str,
    value: &CpuInfo,
) -> zenoh::Result<()> {
    let key = CpuInfo::topic(namespace);
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to the unscoped `CpuInfo` topic and invoke `callback` on updates.
pub async fn subscribe_cpu_info<F>(
    session: Arc<Session>,
    namespace: &str,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(CpuInfo) + Send + 'static,
{
    let key = CpuInfo::topic(namespace);
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<CpuInfo>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `DiskInfo` snapshot to its unscoped zenoh topic.
pub async fn publish_disk_info(
    session: &Session,
    namespace: &str,
    value: &DiskInfo,
) -> zenoh::Result<()> {
    let key = DiskInfo::topic(namespace);
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to the unscoped `DiskInfo` topic and invoke `callback` on updates.
pub async fn subscribe_disk_info<F>(
    session: Arc<Session>,
    namespace: &str,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(DiskInfo) + Send + 'static,
{
    let key = DiskInfo::topic(namespace);
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<DiskInfo>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `GotoCmd` snapshot to `topic`.
/// The caller resolves `GotoCmd::TOPIC_PATTERN` placeholders.
pub async fn publish_goto_cmd(
    session: &Session,
    topic: &str,
    value: &GotoCmd,
) -> zenoh::Result<()> {
    let key = topic.to_string();
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to a pre-resolved `GotoCmd` topic.
/// The caller resolves `GotoCmd::TOPIC_PATTERN` placeholders.
pub async fn subscribe_goto_cmd<F>(
    session: Arc<Session>,
    topic: String,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(GotoCmd) + Send + 'static,
{
    let key = topic.clone();
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<GotoCmd>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `GotoCmdExtended` snapshot to `topic`.
/// The caller resolves `GotoCmdExtended::TOPIC_PATTERN` placeholders.
pub async fn publish_goto_cmd_extended(
    session: &Session,
    topic: &str,
    value: &GotoCmdExtended,
) -> zenoh::Result<()> {
    let key = topic.to_string();
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to a pre-resolved `GotoCmdExtended` topic.
/// The caller resolves `GotoCmdExtended::TOPIC_PATTERN` placeholders.
pub async fn subscribe_goto_cmd_extended<F>(
    session: Arc<Session>,
    topic: String,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(GotoCmdExtended) + Send + 'static,
{
    let key = topic.clone();
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<GotoCmdExtended>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `GpsInjectCmd` snapshot to `topic`.
/// The caller resolves `GpsInjectCmd::TOPIC_PATTERN` placeholders.
pub async fn publish_gps_inject_cmd(
    session: &Session,
    topic: &str,
    value: &GpsInjectCmd,
) -> zenoh::Result<()> {
    let key = topic.to_string();
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to a pre-resolved `GpsInjectCmd` topic.
/// The caller resolves `GpsInjectCmd::TOPIC_PATTERN` placeholders.
pub async fn subscribe_gps_inject_cmd<F>(
    session: Arc<Session>,
    topic: String,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(GpsInjectCmd) + Send + 'static,
{
    let key = topic.clone();
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<GpsInjectCmd>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `MemoryInfo` snapshot to its unscoped zenoh topic.
pub async fn publish_memory_info(
    session: &Session,
    namespace: &str,
    value: &MemoryInfo,
) -> zenoh::Result<()> {
    let key = MemoryInfo::topic(namespace);
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to the unscoped `MemoryInfo` topic and invoke `callback` on updates.
pub async fn subscribe_memory_info<F>(
    session: Arc<Session>,
    namespace: &str,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(MemoryInfo) + Send + 'static,
{
    let key = MemoryInfo::topic(namespace);
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<MemoryInfo>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `MeshModemNode` snapshot to its unscoped zenoh topic.
pub async fn publish_mesh_modem_node(
    session: &Session,
    namespace: &str,
    value: &MeshModemNode,
) -> zenoh::Result<()> {
    let key = MeshModemNode::topic(namespace);
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to the unscoped `MeshModemNode` topic and invoke `callback` on updates.
pub async fn subscribe_mesh_modem_node<F>(
    session: Arc<Session>,
    namespace: &str,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(MeshModemNode) + Send + 'static,
{
    let key = MeshModemNode::topic(namespace);
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<MeshModemNode>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `MeshModemStatus` snapshot to `topic`.
/// The caller resolves `MeshModemStatus::TOPIC_PATTERN` placeholders.
pub async fn publish_mesh_modem_status(
    session: &Session,
    topic: &str,
    value: &MeshModemStatus,
) -> zenoh::Result<()> {
    let key = topic.to_string();
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to a pre-resolved `MeshModemStatus` topic.
/// The caller resolves `MeshModemStatus::TOPIC_PATTERN` placeholders.
pub async fn subscribe_mesh_modem_status<F>(
    session: Arc<Session>,
    topic: String,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(MeshModemStatus) + Send + 'static,
{
    let key = topic.clone();
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<MeshModemStatus>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `NetIface` snapshot to its unscoped zenoh topic.
pub async fn publish_net_iface(
    session: &Session,
    namespace: &str,
    value: &NetIface,
) -> zenoh::Result<()> {
    let key = NetIface::topic(namespace);
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to the unscoped `NetIface` topic and invoke `callback` on updates.
pub async fn subscribe_net_iface<F>(
    session: Arc<Session>,
    namespace: &str,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(NetIface) + Send + 'static,
{
    let key = NetIface::topic(namespace);
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<NetIface>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `SerialStatus` snapshot to its unscoped zenoh topic.
pub async fn publish_serial_status(
    session: &Session,
    namespace: &str,
    value: &SerialStatus,
) -> zenoh::Result<()> {
    let key = SerialStatus::topic(namespace);
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to the unscoped `SerialStatus` topic and invoke `callback` on updates.
pub async fn subscribe_serial_status<F>(
    session: Arc<Session>,
    namespace: &str,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(SerialStatus) + Send + 'static,
{
    let key = SerialStatus::topic(namespace);
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<SerialStatus>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `Telemetry` snapshot to `topic`.
/// The caller resolves `Telemetry::TOPIC_PATTERN` placeholders.
pub async fn publish_telemetry(
    session: &Session,
    topic: &str,
    value: &Telemetry,
) -> zenoh::Result<()> {
    let key = topic.to_string();
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to a pre-resolved `Telemetry` topic.
/// The caller resolves `Telemetry::TOPIC_PATTERN` placeholders.
pub async fn subscribe_telemetry<F>(
    session: Arc<Session>,
    topic: String,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(Telemetry) + Send + 'static,
{
    let key = topic.clone();
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<Telemetry>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/// Publish a `TransmissionDelay` snapshot to its unscoped zenoh topic.
pub async fn publish_transmission_delay(
    session: &Session,
    namespace: &str,
    value: &TransmissionDelay,
) -> zenoh::Result<()> {
    let key = TransmissionDelay::topic(namespace);
    let payload: Vec<u8> = serde_json::to_vec(value).map_err(|e| zenoh::Error::from(format!("json encode: {e}")))?;
    session.put(&key, payload).res().await?;
    Ok(())
}

/// Subscribe to the unscoped `TransmissionDelay` topic and invoke `callback` on updates.
pub async fn subscribe_transmission_delay<F>(
    session: Arc<Session>,
    namespace: &str,
    mut callback: F,
) -> zenoh::Result<()>
where
    F: FnMut(TransmissionDelay) + Send + 'static,
{
    let key = TransmissionDelay::topic(namespace);
    let subscriber = session.declare_subscriber(&key).res().await?;
    tokio::spawn(async move {
        while let Ok(sample) = subscriber.recv_async().await {
            let bytes = sample.value.payload.contiguous().to_vec();
            if let Some(v) = serde_json::from_slice::<TransmissionDelay>(&bytes).ok() {
                callback(v);
            }
        }
    });
    Ok(())
}

/*
 * Suggested Cargo.toml fragment:
 *
 * [dependencies]
 * zenoh = "0.11"
 * serde = { version = "1", features = ["derive"] }
 * serde_json = "1"
 * tokio = { version = "1", features = ["full"] }
 */
