// @alaq/graph-axum — file header / section divider helpers.
//
// The generator emits FIVE files per namespace (see index.ts). Each file
// starts with a small banner identifying the generator + schema + the file
// role. Banners are suppressed when `header: false` — useful for snapshot
// diffs in tests.

import { LineBuffer } from './utils'
// `_version.ts` is a build artifact synced from `package.yaml` by
// `alak/scripts/sync-generator-versions.ts`. Regenerated on every
// `bun run build:types` via the `prebuild:types` hook.
export { GENERATOR_NAME, GENERATOR_VERSION } from './_version'
import { GENERATOR_NAME, GENERATOR_VERSION } from './_version'

/** File role — used in the per-file banner. */
export type FileRole = 'mod' | 'types' | 'handlers' | 'state' | 'routes'

export interface HeaderOptions {
  namespace: string
  schemaVersion: number
  role: FileRole
  header: boolean
}

export function emitFileHeader(buf: LineBuffer, opts: HeaderOptions) {
  if (opts.header) {
    buf.line(`// AUTOGENERATED by ${GENERATOR_NAME} v${GENERATOR_VERSION}`)
    buf.line(`// Schema: ${opts.namespace} v${opts.schemaVersion}`)
    buf.line(`// File role: ${opts.role}`)
    buf.line(`// DO NOT EDIT — regenerate from .aql sources`)
    buf.blank()
  }
  buf.line(`#![allow(dead_code, unused_imports, clippy::all)]`)
  buf.blank()
}

export function emitSection(buf: LineBuffer, title: string) {
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.line(`// ${title}`)
  buf.line(`// ────────────────────────────────────────────────────────────────`)
  buf.blank()
}
