// @alaq/graph-axum — public entry point.
//
// Reads an IR produced by `@alaq/graph` and emits five Rust files per
// namespace, rooted at `<ns_flat>/`:
//
//   <ns_flat>/mod.rs       — public re-exports; pub mod types/handlers/...
//   <ns_flat>/types.rs     — records, enums, <Action>Input / <Action>Output
//   <ns_flat>/handlers.rs  — #[async_trait] trait Handlers
//   <ns_flat>/state.rs     — AppState<H> + manual Clone
//   <ns_flat>/routes.rs    — pub fn router<H: Handlers>(...) + per-action
//                            dispatch_* helpers.
//
// HTTP convention: every action → `POST /<snake_action>`. Outputs are JSON;
// actions with no declared output return `202 Accepted` with an empty body.
//
// Convention (C.1/C.2): snake_case on wire and in Rust. Admin authorization
// is explicitly OUT of scope — handle it with a middleware layered on top
// of the generated router. `@scope(...)` on RECORD is preserved in the
// type-level diagnostics only: we emit a one-time warning per schema when
// scope is seen, to remind the author they are relying on out-of-SDL auth.
//
// Pipeline:
//   compileSources(.aql files) → IR
//   generate(ir)               → GenerateResult   ← this module
//     · <ns>/mod.rs
//     · <ns>/types.rs
//     · <ns>/handlers.rs
//     · <ns>/state.rs
//     · <ns>/routes.rs
//
// No runtime deps. Peer: `@alaq/graph`. The generated Rust code depends on
// `axum`, `serde`, `serde_json`, `async-trait`, and the runtime crate
// configured via `GenerateOptions.runtimeCrate` (default
// `alaq-graph-axum-rt`).

import type { IR, IRSchema } from '@alaq/graph'
import {
  GENERATOR_NAME,
  GENERATOR_VERSION,
  emitFileHeader,
  emitSection,
} from './emit'
import {
  emitActionTypes,
  emitEnums,
  emitRecords,
  emitUserScalars,
} from './types-gen'
import { emitHandlersTrait } from './handlers-gen'
import { emitAppState } from './state-gen'
import { emitRouterFn } from './routes-gen'
import {
  LineBuffer,
  buildTypeContext,
  flattenNamespace,
} from './utils'

// ────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────

export interface GenerateOptions {
  /** Target one namespace. When omitted, every namespace in the IR is emitted. */
  namespace?: string
  /** Emit the AUTOGENERATED banner per file. Default true. */
  header?: boolean
  /** Name of the runtime crate to import from (ActionContext, HandlerError,
   *  async_trait re-export). Default `alaq-graph-axum-rt`. */
  runtimeCrate?: string
}

export interface GenerateDiagnostic {
  severity: 'error' | 'warning'
  message: string
}

export interface GenerateFile {
  path: string
  content: string
}

export interface GenerateResult {
  files: GenerateFile[]
  diagnostics: GenerateDiagnostic[]
}

const DEFAULTS: Required<Omit<GenerateOptions, 'namespace'>> = {
  header: true,
  runtimeCrate: 'alaq_graph_axum_rt',
}

/**
 * v0.3.4 (W8), tightened v0.3.5 (C7): transport kinds this generator emits
 * code for. Compared against `IRSchema.transport` (projected from
 * `@transport(kind: "...")`, SPEC §7.14). Mismatch → E025 error, generator
 * returns `files: []`. `"any"` is always compatible — schemas without
 * `@transport` are treated as `"any"` per R222.
 */
const SUPPORTED_TRANSPORTS: ReadonlyArray<string> = ['http', 'any']

/**
 * Transform an IR into Rust/Axum source files. Pure function: no FS, no
 * network, deterministic for a given IR + options.
 */
export function generate(ir: IR, options: GenerateOptions = {}): GenerateResult {
  // Accept both crate name styles ("alaq-graph-axum-rt", "alaq_graph_axum_rt")
  // and normalize to the underscore form used in Rust `use` paths.
  const runtimeCrate = (options.runtimeCrate ?? DEFAULTS.runtimeCrate).replace(/-/g, '_')
  const opts = {
    header: options.header ?? DEFAULTS.header,
    runtimeCrate,
  }

  const files: GenerateFile[] = []
  const diagnostics: GenerateDiagnostic[] = []

  const namespaces = options.namespace
    ? [options.namespace]
    : Object.keys(ir.schemas).sort()

  for (const ns of namespaces) {
    const schema = ir.schemas[ns]
    if (!schema) {
      diagnostics.push({
        severity: 'error',
        message: `Namespace "${ns}" not found in IR.`,
      })
      continue
    }

    // v0.3.4 (W8), tightened v0.3.5 (C7): E025 on @transport mismatch.
    // `undefined` and `"any"` are compatible (SPEC §7.14 R222). Generation
    // is **refused** on mismatch: we push a single error diagnostic and
    // return an empty file set per SPEC §7.14 R224.
    if (schema.transport && !SUPPORTED_TRANSPORTS.includes(schema.transport)) {
      diagnostics.push({
        severity: 'error',
        message:
          `schema "${schema.namespace}" declares @transport(kind: "${schema.transport}") ` +
          `which is outside @alaq/graph-axum supported transports [${SUPPORTED_TRANSPORTS.join(', ')}]; ` +
          `generation refused (E025). Set @transport(kind: "any") or omit the directive to opt out.`,
      })
      return { files: [], diagnostics }
    }

    generateNamespaceFiles(schema, opts, files, diagnostics)
  }

  return { files, diagnostics }
}

/** v0.3.4 (W8): exported for tests and tooling that want to reflect the
 *  generator's supported set without reaching into internals. */
export { SUPPORTED_TRANSPORTS }

// ────────────────────────────────────────────────────────────────
// Namespace emitter
// ────────────────────────────────────────────────────────────────

function generateNamespaceFiles(
  schema: IRSchema,
  opts: { header: boolean; runtimeCrate: string },
  files: GenerateFile[],
  diagnostics: GenerateDiagnostic[],
) {
  const flat = flattenNamespace(schema.namespace)
  const ctx = buildTypeContext(schema)

  // Advisory: `@scope` on record is preserved in IR but carries no semantics
  // in the HTTP generator. Warn once per schema so authors remember that
  // authorization must be enforced with an out-of-SDL middleware.
  for (const rec of Object.values(schema.records)) {
    if (rec.scope || (rec.directives ?? []).some(d => d.name === 'scope')) {
      diagnostics.push({
        severity: 'warning',
        message:
          `Record "${rec.name}" carries @scope — @alaq/graph-axum v0.1 ignores scope. ` +
          `Enforce admin/auth via an axum middleware layered on top of the generated router.`,
      })
      break
    }
  }

  // Opaque streams and `@scope`/scope-field on actions are similarly outside
  // the v0.1 HTTP surface — emit a single warning summary so the consumer
  // knows.
  if (Object.keys(schema.opaques ?? {}).length > 0) {
    diagnostics.push({
      severity: 'warning',
      message:
        `Schema "${schema.namespace}" declares opaque streams — @alaq/graph-axum v0.1 ignores them ` +
        `(HTTP is request/response; streams belong to a different transport).`,
    })
  }
  for (const a of Object.values(schema.actions)) {
    if (a.scope) {
      diagnostics.push({
        severity: 'warning',
        message:
          `Action "${a.name}" declares scope: "${a.scope}" — @alaq/graph-axum v0.1 ignores action scope. ` +
          `Carry the scope id in the input struct or via middleware.`,
      })
    }
  }
  // v0.3.4 (W9): broadcast events are out of the HTTP/request-response
  // surface. Warn per event so the author is aware that the declaration was
  // seen and skipped — the type itself is not emitted into the Axum module.
  // For a client-facing broadcast surface, generate the same .aql through
  // @alaq/graph-tauri-rs (Tauri IPC) or, once a WebSocket target lands, that
  // one instead.
  for (const ev of Object.values(schema.events)) {
    diagnostics.push({
      severity: 'warning',
      message:
        `Event "${ev.name}" declared — @alaq/graph-axum does not support broadcast events ` +
        `(HTTP is request/response). Consider routing events through a WebSocket / SSE ` +
        `upgrade generator, or pair this schema with @alaq/graph-tauri-rs for a Tauri app.`,
    })
  }

  // mod.rs
  files.push({
    path: `${flat}/mod.rs`,
    content: buildModFile(schema, opts),
  })

  // types.rs
  files.push({
    path: `${flat}/types.rs`,
    content: buildTypesFile(schema, opts, ctx),
  })

  // handlers.rs
  files.push({
    path: `${flat}/handlers.rs`,
    content: buildHandlersFile(schema, opts),
  })

  // state.rs
  files.push({
    path: `${flat}/state.rs`,
    content: buildStateFile(schema, opts),
  })

  // routes.rs
  files.push({
    path: `${flat}/routes.rs`,
    content: buildRoutesFile(schema, opts),
  })
}

// ────────────────────────────────────────────────────────────────
// Per-file builders
// ────────────────────────────────────────────────────────────────

function buildModFile(
  schema: IRSchema,
  opts: { header: boolean; runtimeCrate: string },
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    role: 'mod',
    header: opts.header,
  })
  buf.line(`pub mod types;`)
  buf.line(`pub mod handlers;`)
  buf.line(`pub mod state;`)
  buf.line(`pub mod routes;`)
  buf.blank()
  // Convenience re-exports. `routes::router` is the usual entry point; the
  // others are re-exported so `use rest_valkyrie_arsenal::*;` picks them up.
  buf.line(`pub use handlers::Handlers;`)
  buf.line(`pub use routes::router;`)
  buf.line(`pub use state::AppState;`)
  buf.line(`pub use types::*;`)
  buf.blank()
  return buf.toString()
}

function buildTypesFile(
  schema: IRSchema,
  opts: { header: boolean; runtimeCrate: string },
  ctx: ReturnType<typeof buildTypeContext>,
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    role: 'types',
    header: opts.header,
  })
  buf.line(`use serde::{Serialize, Deserialize};`)
  buf.blank()

  if (Object.keys(schema.scalars).length > 0) {
    emitSection(buf, 'Scalars (user-defined)')
    emitUserScalars(buf, schema.scalars)
  }
  if (Object.keys(schema.enums).length > 0) {
    emitSection(buf, 'Enums')
    emitEnums(buf, schema.enums)
  }
  if (Object.keys(schema.records).length > 0) {
    emitSection(buf, 'Records')
    emitRecords(buf, schema.records, ctx)
  }
  if (Object.keys(schema.actions).length > 0) {
    emitSection(buf, 'Action Input types')
    emitActionTypes(buf, schema.actions, ctx)
  }
  return buf.toString()
}

function buildHandlersFile(
  schema: IRSchema,
  opts: { header: boolean; runtimeCrate: string },
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    role: 'handlers',
    header: opts.header,
  })
  emitSection(buf, 'Handlers trait — implement once per application')
  emitHandlersTrait(buf, schema, opts.runtimeCrate, 'types')
  return buf.toString()
}

function buildStateFile(
  schema: IRSchema,
  opts: { header: boolean; runtimeCrate: string },
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    role: 'state',
    header: opts.header,
  })
  emitSection(buf, 'AppState<H> — thin Arc<H> wrapper, Clone-friendly')
  emitAppState(buf)
  return buf.toString()
}

function buildRoutesFile(
  schema: IRSchema,
  opts: { header: boolean; runtimeCrate: string },
): string {
  const buf = new LineBuffer()
  emitFileHeader(buf, {
    namespace: schema.namespace,
    schemaVersion: schema.version,
    role: 'routes',
    header: opts.header,
  })
  emitSection(buf, 'Router + per-action dispatchers')
  emitRouterFn(buf, schema, opts.runtimeCrate)
  return buf.toString()
}

// Re-export generator identity for caller assertions / tooling.
export { GENERATOR_NAME, GENERATOR_VERSION }
export type { IR, IRSchema, IRRecord, IRAction } from '@alaq/graph'
